"""Observer-independent retarded fields generated by point charges.

This module supplies the electromagnetic field and its complete spacetime
gradient at an explicit observer event. It is intentionally independent of
the observer charge: neutral particles with an intrinsic magnetic moment must
see the same source field as charged particles.

Unlike the legacy chrono-matching force path, every evaluation here solves the
light-cone equation

    c (t_observer - t_source) = |x_observer - x_source(t_source)|

against an interpolated source worldline. A finite-difference gradient calls
that complete evaluator again at all eight displaced events, so the derivative
includes the retarded-time chain rule. Freezing a previously selected source
sample would not be a derivative of a Lienard--Wiechert field.

Only charge-generated fields are constructed. Intrinsic dipole source fields,
their singular self fields, and dipole radiation reaction are deliberately out
of scope for this layer.
"""

from __future__ import annotations

from copy import copy
from dataclasses import dataclass, field as dataclass_field
from math import comb
from typing import Sequence, cast

import numpy as np

from .constants import C_MMNS
from .exact_retarded_backend import require_exact_retarded_backend
from .prepared_history_cache import (
    AppendAwarePreparedHistoryCache,
    history_prepared_buffer_capacity,
    history_storage_capacity,
)
from .rfs import electromagnetic_field_tensor_native
from .types import (
    IndexedTrajectoryArrays,
    Trajectory,
    TrajectoryArrays,
    TrialTrajectoryHistory,
)

TrajectoryHistory = (
    Trajectory | TrajectoryArrays | IndexedTrajectoryArrays | TrialTrajectoryHistory
)

_DEFAULT_ROOT_TOLERANCE_MM = 1.0e-21
_DEFAULT_MAX_ROOT_ITERATIONS = 96
_DEFAULT_GRADIENT_RELATIVE_STEP = 1.0e-4
_DEFAULT_GRADIENT_MINIMUM_STEP_MM = 1.0e-15


class RetardedHistoryError(ValueError):
    """Raised when a source history does not bracket a retarded event."""


@dataclass(frozen=True)
class ObserverEvent:
    """One observer event in the solver's millimetre/nanosecond units."""

    time_ns: float
    position_mm: tuple[float, float, float]

    def __post_init__(self) -> None:
        time = float(self.time_ns)
        position = np.asarray(self.position_mm, dtype=float)
        if not np.isfinite(time):
            raise ValueError("observer time must be finite")
        if position.shape != (3,) or not np.all(np.isfinite(position)):
            raise ValueError("observer position must contain three finite values")


@dataclass(frozen=True)
class RetardedChargeFieldResult:
    """Total native Gaussian charge potential, field, and diagnostics.

    ``four_potential`` is the contravariant Lienard--Wiechert potential
    ``A^mu=(phi, phi beta)`` in the gauge selected by the retarded point-charge
    solution.  It is appended with a default to preserve compatibility with
    older direct dataclass constructors.
    """

    electric_field_native: np.ndarray
    magnetic_field_native: np.ndarray
    field_tensor: np.ndarray
    retarded_time_ns: np.ndarray
    light_cone_residual_mm: np.ndarray
    separation_mm: np.ndarray
    valid_sources: np.ndarray
    four_potential: np.ndarray = dataclass_field(
        default_factory=lambda: np.zeros(4, dtype=float)
    )


@dataclass(frozen=True)
class RetardedChargeFieldGradientResult:
    """A native charge field and its complete potential/field derivatives.

    ``partial_a[lambda, nu]`` is ``partial_lambda A^nu`` per millimetre and
    uses the same eight independently retarded stencil events as
    ``partial_f``.  It is appended with a default to preserve compatibility
    with older direct dataclass constructors.
    """

    field: RetardedChargeFieldResult
    partial_f: np.ndarray
    stencil_step_mm: float
    stencil_retarded_time_ns: np.ndarray
    partial_a: np.ndarray = dataclass_field(
        default_factory=lambda: np.zeros((4, 4), dtype=float)
    )


@dataclass(frozen=True)
class RetardedChargeResponseGradientResult:
    """Potential plus the independent coefficients of ``F`` and ``partial F``.

    The analytical path keeps only the six antisymmetric coefficients and
    their four directional derivatives.  ``fallback_used`` is true when the
    retarded root is too close to an interpolation-segment boundary for the
    within-segment derivative to be authoritative; in that case the values
    are packed from the maintained centered-stencil provider.
    """

    four_potential: np.ndarray
    partial_a: np.ndarray
    antisymmetric_response: np.ndarray
    partial_antisymmetric_response: np.ndarray
    retarded_time_ns: np.ndarray
    light_cone_residual_mm: np.ndarray
    separation_mm: np.ndarray
    valid_sources: np.ndarray
    kappa: np.ndarray
    segment_index: np.ndarray
    minimum_segment_margin_ratio: float
    fallback_used: bool
    fallback_reason: str | None
    fallback_stencil_step_mm: float | None


@dataclass
class _HistoryArrays:
    time_ns: np.ndarray
    position_mm: np.ndarray
    beta: np.ndarray
    beta_prime_per_mm: np.ndarray
    charge_native: np.ndarray
    dead: np.ndarray
    _time_buffer: np.ndarray | None = dataclass_field(default=None, repr=False)
    _position_buffer: np.ndarray | None = dataclass_field(default=None, repr=False)
    _beta_buffer: np.ndarray | None = dataclass_field(default=None, repr=False)
    _beta_prime_buffer: np.ndarray | None = dataclass_field(default=None, repr=False)
    _dead_buffer: np.ndarray | None = dataclass_field(default=None, repr=False)
    _maximum_capacity: int | None = dataclass_field(default=None, repr=False)

    @property
    def n_sources(self) -> int:
        return int(self.time_ns.shape[1])


@dataclass
class _PreparedSourceHistory:
    """One alive source prefix with reusable quintic segment coefficients."""

    source_index: int
    time_ns: np.ndarray
    position_mm: np.ndarray
    beta: np.ndarray
    beta_prime_per_mm: np.ndarray
    segment_duration_ns: np.ndarray
    position_coefficients_mm: np.ndarray
    ended_by_loss: bool
    _duration_buffer: np.ndarray | None = dataclass_field(default=None, repr=False)
    _coefficient_buffer: np.ndarray | None = dataclass_field(default=None, repr=False)
    _maximum_capacity: int | None = dataclass_field(default=None, repr=False)
    _metal_timelike_count: int = dataclass_field(default=0, repr=False)
    _metal_timelike_proof: bool = dataclass_field(default=True, repr=False)


@dataclass(frozen=True)
class _PreparedHistory:
    """Extracted history and the non-excluded charged source interpolants."""

    arrays: _HistoryArrays
    sources: dict[int, _PreparedSourceHistory]


_CHARGE_PREPARED_HISTORY_CACHE: AppendAwarePreparedHistoryCache[
    TrajectoryHistory, _PreparedHistory
] = AppendAwarePreparedHistoryCache(max_entries=2)


@dataclass(frozen=True)
class _RetardedSample:
    time_ns: float
    position_mm: np.ndarray
    beta: np.ndarray
    beta_prime_per_mm: np.ndarray
    residual_mm: float
    separation_mm: float


@dataclass(frozen=True)
class _RootTrialDecision:
    """One safeguarded Newton step and how its bracket protection was used."""

    time_ns: float
    used_bisection: bool
    used_nextafter: bool


def _legacy_matrix(history: Trajectory, field_name: str) -> np.ndarray:
    return np.stack(
        [np.asarray(state[field_name], dtype=float) for state in history],
        axis=0,
    )


def _legacy_constant(history: Trajectory, field_name: str) -> np.ndarray:
    if not history:
        return np.zeros(0, dtype=float)
    return np.asarray(history[-1][field_name], dtype=float)


def _require_current_history_storage(history: TrajectoryHistory) -> None:
    if isinstance(history, TrialTrajectoryHistory):
        history.base.require_current_storage()
    elif isinstance(history, IndexedTrajectoryArrays):
        history.base.require_current_storage()
    elif isinstance(history, TrajectoryArrays):
        history.require_current_storage()


def _history_matrix(history: TrajectoryHistory, field_name: str) -> np.ndarray:
    _require_current_history_storage(history)
    if isinstance(history, TrialTrajectoryHistory):
        raise TypeError("trial history must use the prepared overlay path")
    if isinstance(history, IndexedTrajectoryArrays):
        start = int(history.start_step)
        values = np.asarray(getattr(history.base, field_name), dtype=float)[start:]
        return np.asarray(values[:, history.particle_indices], dtype=float)
    if isinstance(history, TrajectoryArrays):
        return np.asarray(getattr(history, field_name), dtype=float)
    return _legacy_matrix(history, field_name)


def _history_constant(history: TrajectoryHistory, field_name: str) -> np.ndarray:
    _require_current_history_storage(history)
    if isinstance(history, TrialTrajectoryHistory):
        return np.asarray(getattr(history.base, field_name), dtype=float)
    if isinstance(history, IndexedTrajectoryArrays):
        return np.asarray(history.constant(field_name), dtype=float)
    if isinstance(history, TrajectoryArrays):
        return np.asarray(getattr(history, field_name), dtype=float)
    return _legacy_constant(history, field_name)


def _history_dead(history: TrajectoryHistory, shape: tuple[int, int]) -> np.ndarray:
    _require_current_history_storage(history)
    if isinstance(history, TrialTrajectoryHistory):
        raise TypeError("trial history must use the prepared overlay path")
    if isinstance(history, IndexedTrajectoryArrays):
        start = int(history.start_step)
        dead = np.asarray(history.base.dead, dtype=bool)[start:]
        return np.asarray(dead[:, history.particle_indices], dtype=bool)
    if isinstance(history, TrajectoryArrays):
        return np.asarray(history.dead, dtype=bool)
    rows = [
        np.asarray(
            state.get("_dead_particles", np.zeros(shape[1], dtype=bool)),
            dtype=bool,
        )
        for state in history
    ]
    return np.stack(rows, axis=0) if rows else np.zeros(shape, dtype=bool)


def _source_charge_native(history: TrajectoryHistory) -> np.ndarray:
    for field_name in ("q_source", "q"):
        try:
            return _history_constant(history, field_name)
        except (AttributeError, KeyError):
            continue
    raise ValueError("source history must provide q_source or q")


def _extract_history(history: TrajectoryHistory) -> _HistoryArrays:
    if isinstance(history, list) and not history:
        return _HistoryArrays(
            time_ns=np.zeros((0, 0)),
            position_mm=np.zeros((0, 0, 3)),
            beta=np.zeros((0, 0, 3)),
            beta_prime_per_mm=np.zeros((0, 0, 3)),
            charge_native=np.zeros(0),
            dead=np.zeros((0, 0), dtype=bool),
        )

    time_ns = _history_matrix(history, "t")
    x_mm = _history_matrix(history, "x")
    y_mm = _history_matrix(history, "y")
    z_mm = _history_matrix(history, "z")
    bx = _history_matrix(history, "bx")
    by = _history_matrix(history, "by")
    bz = _history_matrix(history, "bz")
    bdotx = _history_matrix(history, "bdotx")
    bdoty = _history_matrix(history, "bdoty")
    bdotz = _history_matrix(history, "bdotz")
    matrices = (x_mm, y_mm, z_mm, bx, by, bz, bdotx, bdoty, bdotz)
    if time_ns.ndim != 2 or any(matrix.shape != time_ns.shape for matrix in matrices):
        raise ValueError("source history fields must share shape [steps, particles]")
    if not all(np.all(np.isfinite(matrix)) for matrix in (time_ns, *matrices)):
        raise ValueError("source history kinematics must be finite")

    charge_native = np.asarray(_source_charge_native(history), dtype=float)
    if charge_native.shape != (time_ns.shape[1],):
        raise ValueError("source charge array must match the particle count")
    if not np.all(np.isfinite(charge_native)):
        raise ValueError("source charge array must contain only finite values")
    position_mm = np.stack((x_mm, y_mm, z_mm), axis=-1)
    beta = np.stack((bx, by, bz), axis=-1)
    # Stored bdot is d beta / d(ct), where ct is measured in millimetres.
    beta_prime_per_mm = np.stack((bdotx, bdoty, bdotz), axis=-1)
    dead = _history_dead(history, time_ns.shape)
    return _HistoryArrays(
        time_ns=time_ns,
        position_mm=position_mm,
        beta=beta,
        beta_prime_per_mm=beta_prime_per_mm,
        charge_native=charge_native,
        dead=dead,
    )


def _reserve_history_arrays(
    arrays: _HistoryArrays,
    capacity: int | None,
    *,
    maximum_capacity: int | None = None,
) -> _HistoryArrays:
    """Move visible rows into fixed-capacity append buffers when requested."""

    visible_stop = int(arrays.time_ns.shape[0])
    if capacity is None:
        return arrays
    if maximum_capacity is not None:
        arrays._maximum_capacity = max(visible_stop, int(maximum_capacity))
    limit = arrays._maximum_capacity
    requested = max(visible_stop, int(capacity))
    reserved = requested if limit is None else min(requested, limit)
    n_sources = arrays.n_sources
    time_buffer = np.empty((reserved, n_sources), dtype=float)
    position_buffer = np.empty((reserved, n_sources, 3), dtype=float)
    beta_buffer = np.empty((reserved, n_sources, 3), dtype=float)
    beta_prime_buffer = np.empty((reserved, n_sources, 3), dtype=float)
    dead_buffer = np.empty((reserved, n_sources), dtype=bool)
    time_buffer[:visible_stop] = arrays.time_ns
    position_buffer[:visible_stop] = arrays.position_mm
    beta_buffer[:visible_stop] = arrays.beta
    beta_prime_buffer[:visible_stop] = arrays.beta_prime_per_mm
    dead_buffer[:visible_stop] = arrays.dead
    arrays.time_ns = time_buffer[:visible_stop]
    arrays.position_mm = position_buffer[:visible_stop]
    arrays.beta = beta_buffer[:visible_stop]
    arrays.beta_prime_per_mm = beta_prime_buffer[:visible_stop]
    arrays.dead = dead_buffer[:visible_stop]
    arrays.charge_native = np.array(arrays.charge_native, dtype=float, copy=True)
    arrays._time_buffer = time_buffer
    arrays._position_buffer = position_buffer
    arrays._beta_buffer = beta_buffer
    arrays._beta_prime_buffer = beta_prime_buffer
    arrays._dead_buffer = dead_buffer
    return arrays


def _history_matrix_slice(
    history: TrajectoryHistory,
    field_name: str,
    start_step: int,
) -> np.ndarray:
    """Extract only a newly visible tail from one history field."""

    _require_current_history_storage(history)
    start = int(start_step)
    if isinstance(history, TrialTrajectoryHistory):
        raise TypeError("trial history must use the prepared overlay path")
    if isinstance(history, IndexedTrajectoryArrays):
        global_start = int(history.start_step) + start
        values = np.asarray(getattr(history.base, field_name), dtype=float)[
            global_start : history.base.n_steps
        ]
        return np.asarray(values[:, history.particle_indices], dtype=float)
    if isinstance(history, TrajectoryArrays):
        return np.asarray(getattr(history, field_name), dtype=float)[start:]
    return _legacy_matrix(history[start:], field_name)


def _history_dead_slice(
    history: TrajectoryHistory,
    start_step: int,
    shape: tuple[int, int],
) -> np.ndarray:
    _require_current_history_storage(history)
    start = int(start_step)
    if isinstance(history, TrialTrajectoryHistory):
        raise TypeError("trial history must use the prepared overlay path")
    if isinstance(history, IndexedTrajectoryArrays):
        global_start = int(history.start_step) + start
        dead = np.asarray(history.base.dead, dtype=bool)[
            global_start : history.base.n_steps
        ]
        return np.asarray(dead[:, history.particle_indices], dtype=bool)
    if isinstance(history, TrajectoryArrays):
        return np.asarray(history.dead, dtype=bool)[start:]
    rows = [
        np.asarray(
            state.get("_dead_particles", np.zeros(shape[1], dtype=bool)),
            dtype=bool,
        )
        for state in history[start:]
    ]
    return np.stack(rows, axis=0) if rows else np.zeros(shape, dtype=bool)


def _extract_history_tail(
    history: TrajectoryHistory,
    start_step: int,
) -> _HistoryArrays:
    """Validate and extract only rows at or after ``start_step``."""

    time_ns = _history_matrix_slice(history, "t", start_step)
    x_mm = _history_matrix_slice(history, "x", start_step)
    y_mm = _history_matrix_slice(history, "y", start_step)
    z_mm = _history_matrix_slice(history, "z", start_step)
    bx = _history_matrix_slice(history, "bx", start_step)
    by = _history_matrix_slice(history, "by", start_step)
    bz = _history_matrix_slice(history, "bz", start_step)
    bdotx = _history_matrix_slice(history, "bdotx", start_step)
    bdoty = _history_matrix_slice(history, "bdoty", start_step)
    bdotz = _history_matrix_slice(history, "bdotz", start_step)
    matrices = (x_mm, y_mm, z_mm, bx, by, bz, bdotx, bdoty, bdotz)
    if time_ns.ndim != 2 or any(matrix.shape != time_ns.shape for matrix in matrices):
        raise ValueError("source history fields must share shape [steps, particles]")
    if not all(np.all(np.isfinite(matrix)) for matrix in (time_ns, *matrices)):
        raise ValueError("source history kinematics must be finite")
    charge_native = np.asarray(_source_charge_native(history), dtype=float)
    if charge_native.shape != (time_ns.shape[1],):
        raise ValueError("source charge array must match the particle count")
    if not np.all(np.isfinite(charge_native)):
        raise ValueError("source charge array must contain only finite values")
    return _HistoryArrays(
        time_ns=time_ns,
        position_mm=np.stack((x_mm, y_mm, z_mm), axis=-1),
        beta=np.stack((bx, by, bz), axis=-1),
        beta_prime_per_mm=np.stack((bdotx, bdoty, bdotz), axis=-1),
        charge_native=charge_native,
        dead=_history_dead_slice(history, start_step, time_ns.shape),
    )


def _append_history_arrays(
    previous: _HistoryArrays,
    history: TrajectoryHistory,
    old_stop: int,
) -> _HistoryArrays:
    """Extend extracted arrays from the newly visible history tail."""

    tail = _extract_history_tail(history, old_stop)
    if tail.n_sources != previous.n_sources:
        raise ValueError("source particle count changed while appending history")
    if not np.array_equal(tail.charge_native, previous.charge_native):
        return _extract_history(history)

    tail_count = int(tail.time_ns.shape[0])
    new_stop = int(old_stop) + tail_count
    buffers = (
        previous._time_buffer,
        previous._position_buffer,
        previous._beta_buffer,
        previous._beta_prime_buffer,
        previous._dead_buffer,
    )
    if any(buffer is None for buffer in buffers):
        # Append is normally reached only through a builder-managed cached
        # history. Keep this private helper safe for direct test/research use.
        _reserve_history_arrays(previous, max(new_stop, max(1, 2 * int(old_stop))))
    assert previous._time_buffer is not None
    assert previous._position_buffer is not None
    assert previous._beta_buffer is not None
    assert previous._beta_prime_buffer is not None
    assert previous._dead_buffer is not None
    capacity = int(previous._time_buffer.shape[0])
    if new_stop > capacity:
        _reserve_history_arrays(previous, max(new_stop, max(8, 2 * capacity)))
        assert previous._time_buffer is not None
        assert previous._position_buffer is not None
        assert previous._beta_buffer is not None
        assert previous._beta_prime_buffer is not None
        assert previous._dead_buffer is not None
        if new_stop > previous._time_buffer.shape[0]:
            raise ValueError("prepared history append exceeded builder capacity")

    previous._time_buffer[old_stop:new_stop] = tail.time_ns
    previous._position_buffer[old_stop:new_stop] = tail.position_mm
    previous._beta_buffer[old_stop:new_stop] = tail.beta
    previous._beta_prime_buffer[old_stop:new_stop] = tail.beta_prime_per_mm
    previous._dead_buffer[old_stop:new_stop] = tail.dead
    previous.time_ns = previous._time_buffer[:new_stop]
    previous.position_mm = previous._position_buffer[:new_stop]
    previous.beta = previous._beta_buffer[:new_stop]
    previous.beta_prime_per_mm = previous._beta_prime_buffer[:new_stop]
    previous.dead = previous._dead_buffer[:new_stop]
    return previous


def _append_history_array_tail(
    previous: _HistoryArrays,
    tail: _HistoryArrays,
) -> tuple[_HistoryArrays, int]:
    """Return a private prepared-array clone extended by a tiny trial tail."""

    old_stop = int(previous.time_ns.shape[0])
    tail_count = int(tail.time_ns.shape[0])
    if tail_count not in {1, 2}:
        raise ValueError("prepared trial tail must contain one or two rows")
    if tail.n_sources != previous.n_sources:
        raise ValueError("trial source particle count changed")
    if not np.array_equal(tail.charge_native, previous.charge_native):
        raise ValueError("trial source charge changed")

    extended = copy(previous)
    new_stop = old_stop + tail_count
    existing_capacity = (
        0 if extended._time_buffer is None else int(extended._time_buffer.shape[0])
    )
    extended._maximum_capacity = max(
        new_stop,
        int(extended._maximum_capacity or old_stop),
    )
    if existing_capacity < new_stop:
        _reserve_history_arrays(
            extended,
            max(new_stop, max(8, 2 * existing_capacity)),
            maximum_capacity=extended._maximum_capacity,
        )
    assert extended._time_buffer is not None
    assert extended._position_buffer is not None
    assert extended._beta_buffer is not None
    assert extended._beta_prime_buffer is not None
    assert extended._dead_buffer is not None
    extended._time_buffer[old_stop:new_stop] = tail.time_ns
    extended._position_buffer[old_stop:new_stop] = tail.position_mm
    extended._beta_buffer[old_stop:new_stop] = tail.beta
    extended._beta_prime_buffer[old_stop:new_stop] = tail.beta_prime_per_mm
    extended._dead_buffer[old_stop:new_stop] = tail.dead
    extended.time_ns = extended._time_buffer[:new_stop]
    extended.position_mm = extended._position_buffer[:new_stop]
    extended.beta = extended._beta_buffer[:new_stop]
    extended.beta_prime_per_mm = extended._beta_prime_buffer[:new_stop]
    extended.dead = extended._dead_buffer[:new_stop]
    return extended, old_stop


def _prepare_trial_history(
    history: TrialTrajectoryHistory,
    excluded_source_indices: Sequence[int],
) -> _PreparedHistory:
    """Extend cached accepted charge history without publishing trial knots."""

    accepted = _prepare_history(history.base, excluded_source_indices)
    tail_arrays = _extract_history(list(history.tail))
    arrays, old_stop = _append_history_array_tail(accepted.arrays, tail_arrays)
    sources: dict[int, _PreparedSourceHistory] = {}
    for source_index, source in accepted.sources.items():
        trial_source = copy(source)
        trial_source._maximum_capacity = arrays._maximum_capacity
        _append_prepared_source_history(trial_source, arrays, old_stop)
        sources[source_index] = trial_source
    return _PreparedHistory(arrays=arrays, sources=sources)


def _quintic_worldline_sample(
    source: _PreparedSourceHistory,
    segment_index: int,
    time_ns: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Interpolate position, velocity, and acceleration continuously."""

    t0 = float(source.time_ns[segment_index])
    duration = float(source.segment_duration_ns[segment_index])
    tau = float(np.clip((time_ns - t0) / duration, 0.0, 1.0))
    c0, c1, c2, c3, c4, c5 = source.position_coefficients_mm[segment_index]

    position = c0 + c1 * tau + c2 * tau**2 + c3 * tau**3 + c4 * tau**4 + c5 * tau**5
    velocity = (
        c1 + 2.0 * c2 * tau + 3.0 * c3 * tau**2 + 4.0 * c4 * tau**3 + 5.0 * c5 * tau**4
    ) / duration
    acceleration = (
        2.0 * c2 + 6.0 * c3 * tau + 12.0 * c4 * tau**2 + 20.0 * c5 * tau**3
    ) / duration**2
    return position, velocity / C_MMNS, acceleration / C_MMNS**2


def _light_cone_residual_mm(
    *,
    observer_time_ns: float,
    observer_position_mm: np.ndarray,
    source_time_ns: float,
    source_position_mm: np.ndarray,
) -> tuple[float, float]:
    separation = float(np.linalg.norm(observer_position_mm - source_position_mm))
    residual = C_MMNS * (observer_time_ns - source_time_ns) - separation
    return residual, separation


def _alive_prefix_length(history: _HistoryArrays, source_index: int) -> int:
    """Return the number of source samples before its first loss marker."""

    dead = np.asarray(history.dead[:, source_index], dtype=bool)
    dead_indices = np.flatnonzero(dead)
    if dead_indices.size == 0:
        return int(dead.size)
    first_dead = int(dead_indices[0])
    if np.any(~dead[first_dead:]):
        raise ValueError("source dead-state history must remain dead after loss")
    return first_dead


def _quintic_position_coefficients_mm(
    times: np.ndarray,
    positions: np.ndarray,
    betas: np.ndarray,
    beta_primes: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Return segment durations and quintic worldline coefficients."""

    durations = np.diff(times)
    if np.any(durations <= 0.0):
        raise ValueError("source coordinate times must be strictly increasing")

    if durations.size == 0:
        coefficients = np.zeros((0, 6, 3), dtype=float)
    else:
        duration_columns = durations[:, np.newaxis]
        velocity_0 = C_MMNS * betas[:-1]
        velocity_1 = C_MMNS * betas[1:]
        acceleration_0 = C_MMNS**2 * beta_primes[:-1]
        acceleration_1 = C_MMNS**2 * beta_primes[1:]
        c0 = positions[:-1]
        c1 = duration_columns * velocity_0
        c2 = 0.5 * duration_columns**2 * acceleration_0
        position_remainder = positions[1:] - c0 - c1 - c2
        velocity_remainder = duration_columns * velocity_1 - c1 - 2.0 * c2
        acceleration_remainder = duration_columns**2 * acceleration_1 - 2.0 * c2
        c3 = (
            10.0 * position_remainder
            - 4.0 * velocity_remainder
            + 0.5 * acceleration_remainder
        )
        c4 = (
            -15.0 * position_remainder
            + 7.0 * velocity_remainder
            - acceleration_remainder
        )
        c5 = (
            6.0 * position_remainder
            - 3.0 * velocity_remainder
            + 0.5 * acceleration_remainder
        )
        coefficients = np.stack((c0, c1, c2, c3, c4, c5), axis=1)

    return durations, coefficients


def _prepare_source_history(
    history: _HistoryArrays,
    source_index: int,
    *,
    reserve_capacity: int | None = None,
) -> _PreparedSourceHistory:
    """Validate and prepare one source's alive interpolation segments."""

    alive_stop = _alive_prefix_length(history, source_index)
    times = history.time_ns[:alive_stop, source_index]
    positions = history.position_mm[:alive_stop, source_index]
    betas = history.beta[:alive_stop, source_index]
    beta_primes = history.beta_prime_per_mm[:alive_stop, source_index]
    durations, coefficients = _quintic_position_coefficients_mm(
        times,
        positions,
        betas,
        beta_primes,
    )
    prepared = _PreparedSourceHistory(
        source_index=source_index,
        time_ns=times,
        position_mm=positions,
        beta=betas,
        beta_prime_per_mm=beta_primes,
        segment_duration_ns=durations,
        position_coefficients_mm=coefficients,
        ended_by_loss=alive_stop != history.time_ns.shape[0],
        _maximum_capacity=history._maximum_capacity,
    )
    if reserve_capacity is None:
        return prepared

    knot_capacity = max(alive_stop, int(reserve_capacity))
    segment_capacity = max(0, knot_capacity - 1)
    duration_buffer = np.empty(segment_capacity, dtype=float)
    coefficient_buffer = np.empty((segment_capacity, 6, 3), dtype=float)
    segment_stop = int(durations.size)
    duration_buffer[:segment_stop] = durations
    coefficient_buffer[:segment_stop] = coefficients
    prepared.segment_duration_ns = duration_buffer[:segment_stop]
    prepared.position_coefficients_mm = coefficient_buffer[:segment_stop]
    prepared._duration_buffer = duration_buffer
    prepared._coefficient_buffer = coefficient_buffer
    return prepared


def _append_prepared_source_history(
    previous: _PreparedSourceHistory,
    history: _HistoryArrays,
    old_stop: int,
) -> _PreparedSourceHistory:
    """Append alive knots and only their new quintic segments."""

    source_index = previous.source_index
    tail_dead = np.asarray(history.dead[old_stop:, source_index], dtype=bool)
    if previous.ended_by_loss:
        if np.any(~tail_dead):
            raise ValueError("source dead-state history must remain dead after loss")
        return previous
    dead_indices = np.flatnonzero(tail_dead)
    if dead_indices.size:
        first_dead = int(dead_indices[0])
        if np.any(~tail_dead[first_dead:]):
            raise ValueError("source dead-state history must remain dead after loss")
        append_alive = first_dead
        ended_by_loss = True
    else:
        append_alive = int(tail_dead.size)
        ended_by_loss = False

    new_alive_stop = int(old_stop) + append_alive
    if append_alive == 0:
        previous.ended_by_loss = ended_by_loss
        return previous

    old_alive_stop = int(previous.time_ns.size)
    coefficient_start = max(0, old_alive_stop - 1)
    new_durations, new_coefficients = _quintic_position_coefficients_mm(
        history.time_ns[coefficient_start:new_alive_stop, source_index],
        history.position_mm[coefficient_start:new_alive_stop, source_index],
        history.beta[coefficient_start:new_alive_stop, source_index],
        history.beta_prime_per_mm[coefficient_start:new_alive_stop, source_index],
    )
    required_segment_capacity = max(0, new_alive_stop - 1)
    current_segment_capacity = (
        0 if previous._duration_buffer is None else int(previous._duration_buffer.size)
    )
    if (
        previous._duration_buffer is None
        or previous._coefficient_buffer is None
        or required_segment_capacity > current_segment_capacity
    ):
        segment_capacity = max(
            required_segment_capacity,
            max(7, 2 * current_segment_capacity),
        )
        if previous._maximum_capacity is not None:
            segment_capacity = min(
                segment_capacity,
                max(0, previous._maximum_capacity - 1),
            )
        duration_buffer = np.empty(segment_capacity, dtype=float)
        coefficient_buffer = np.empty((segment_capacity, 6, 3), dtype=float)
        old_segment_stop = int(previous.segment_duration_ns.size)
        duration_buffer[:old_segment_stop] = previous.segment_duration_ns
        coefficient_buffer[:old_segment_stop] = previous.position_coefficients_mm
        previous._duration_buffer = duration_buffer
        previous._coefficient_buffer = coefficient_buffer
    segment_start = max(0, old_alive_stop - 1)
    segment_stop = max(0, new_alive_stop - 1)
    assert previous._duration_buffer is not None
    assert previous._coefficient_buffer is not None
    if segment_stop > previous._duration_buffer.size:
        raise ValueError("prepared source append exceeded builder capacity")
    previous._duration_buffer[segment_start:segment_stop] = new_durations
    previous._coefficient_buffer[segment_start:segment_stop] = new_coefficients
    previous.time_ns = history.time_ns[:new_alive_stop, source_index]
    previous.position_mm = history.position_mm[:new_alive_stop, source_index]
    previous.beta = history.beta[:new_alive_stop, source_index]
    previous.beta_prime_per_mm = history.beta_prime_per_mm[
        :new_alive_stop, source_index
    ]
    previous.segment_duration_ns = previous._duration_buffer[:segment_stop]
    previous.position_coefficients_mm = previous._coefficient_buffer[:segment_stop]
    previous.ended_by_loss = ended_by_loss
    return previous


def _prepare_history_uncached(
    history: TrajectoryHistory,
    excluded_source_indices: Sequence[int],
    *,
    reserve_capacity: int | None = None,
    maximum_capacity: int | None = None,
) -> _PreparedHistory:
    """Extract once and prepare only sources that can contribute a field."""

    arrays = _reserve_history_arrays(
        _extract_history(history),
        reserve_capacity,
        maximum_capacity=maximum_capacity,
    )
    excluded = {int(index) for index in excluded_source_indices}
    if any(index < 0 or index >= arrays.n_sources for index in excluded):
        raise IndexError("excluded source index is out of bounds")
    sources = {
        source_index: _prepare_source_history(
            arrays,
            source_index,
            reserve_capacity=reserve_capacity,
        )
        for source_index in range(arrays.n_sources)
        if source_index not in excluded
        and abs(arrays.charge_native[source_index]) != 0.0
    }
    return _PreparedHistory(arrays=arrays, sources=sources)


def _append_prepared_history(
    previous: _PreparedHistory,
    history: TrajectoryHistory,
    old_stop: int,
    excluded_source_indices: Sequence[int] = (),
) -> _PreparedHistory:
    """Extend charged-source preparation from one builder history tail."""

    arrays = _append_history_arrays(previous.arrays, history, old_stop)
    # A changed constant forces _append_history_arrays to re-extract the full
    # history. Rebuild source selection as well instead of treating it as an
    # append under stale charges.
    if not np.array_equal(arrays.charge_native, previous.arrays.charge_native):
        return _prepare_history_uncached(
            history,
            excluded_source_indices,
            reserve_capacity=history_prepared_buffer_capacity(history),
            maximum_capacity=history_storage_capacity(history),
        )
    for source in previous.sources.values():
        _append_prepared_source_history(source, arrays, old_stop)
    return previous


def _prepare_history(
    history: TrajectoryHistory,
    excluded_source_indices: Sequence[int],
) -> _PreparedHistory:
    """Prepare charged histories, extending a safe builder-backed cache."""

    if isinstance(history, TrialTrajectoryHistory):
        return _prepare_trial_history(history, excluded_source_indices)
    excluded = tuple(sorted({int(index) for index in excluded_source_indices}))
    return _CHARGE_PREPARED_HISTORY_CACHE.prepare(
        history,
        variant=("charge", excluded),
        prepare_full=lambda current: _prepare_history_uncached(
            current,
            excluded,
            reserve_capacity=history_prepared_buffer_capacity(current),
            maximum_capacity=history_storage_capacity(current),
        ),
        append=lambda previous, current, old_stop: _append_prepared_history(
            previous,
            current,
            old_stop,
            excluded,
        ),
    ).value


def _next_safeguarded_root_trial(
    *,
    trial_time_ns: float,
    residual_mm: float,
    derivative_mm_per_ns: float,
    lower_time_ns: float,
    upper_time_ns: float,
) -> _RootTrialDecision:
    """Take an in-bracket Newton step, or bisect when that step is unsafe."""

    available_time = (
        upper_time_ns - trial_time_ns
        if residual_mm > 0.0
        else trial_time_ns - lower_time_ns
    )
    maximum_newton_residual = -derivative_mm_per_ns * available_time
    if (
        np.isfinite(derivative_mm_per_ns)
        and derivative_mm_per_ns < 0.0
        and np.isfinite(maximum_newton_residual)
        and abs(residual_mm) < maximum_newton_residual
    ):
        next_trial = trial_time_ns - residual_mm / derivative_mm_per_ns
    else:
        next_trial = float("nan")
    if next_trial == trial_time_ns:
        target = upper_time_ns if residual_mm > 0.0 else lower_time_ns
        return _RootTrialDecision(
            time_ns=float(np.nextafter(trial_time_ns, target)),
            used_bisection=False,
            used_nextafter=True,
        )
    if (
        not np.isfinite(next_trial)
        or next_trial <= lower_time_ns
        or next_trial >= upper_time_ns
    ):
        return _RootTrialDecision(
            time_ns=0.5 * (lower_time_ns + upper_time_ns),
            used_bisection=True,
            used_nextafter=False,
        )
    return _RootTrialDecision(
        time_ns=next_trial,
        used_bisection=False,
        used_nextafter=False,
    )


def _knot_light_cone_residual_mm(
    source: _PreparedSourceHistory,
    knot_index: int,
    *,
    observer_time_ns: float,
    observer_position_mm: np.ndarray,
) -> float:
    """Return the light-cone residual at one stored source knot.

    For a timelike source history this residual is monotonically decreasing
    with source time.  Keeping the scalar evaluation separate makes the
    bracketing cost directly testable and avoids allocating a full-history
    separation vector for every retarded-field stencil event.
    """

    separation_mm = float(
        np.linalg.norm(observer_position_mm - source.position_mm[knot_index])
    )
    return float(
        C_MMNS * (observer_time_ns - float(source.time_ns[knot_index])) - separation_mm
    )


def _find_retarded_knot_bracket(
    source: _PreparedSourceHistory,
    *,
    observer_time_ns: float,
    observer_position_mm: np.ndarray,
) -> int | None:
    """Return the latest knot segment bracketing the retarded event.

    The source worldline is timelike, so

    ``g(t_s) = c (t_observer - t_s) - |x_observer - x_source(t_s)|``

    decreases monotonically at its stored knots.  Binary search therefore
    finds the same latest ``g[j] >= 0 >= g[j + 1]`` segment as the historical
    full scan in ``O(log n)`` scalar residual evaluations.  Treating an exact
    internal-knot root as the lower endpoint selects the following segment,
    matching the old ``brackets[-1]`` convention.
    """

    knot_count = int(source.time_ns.size)
    if knot_count < 2:
        return None

    lower = 0
    upper = knot_count - 1
    lower_residual = _knot_light_cone_residual_mm(
        source,
        lower,
        observer_time_ns=observer_time_ns,
        observer_position_mm=observer_position_mm,
    )
    if lower_residual < 0.0:
        return None

    upper_residual = _knot_light_cone_residual_mm(
        source,
        upper,
        observer_time_ns=observer_time_ns,
        observer_position_mm=observer_position_mm,
    )
    if upper_residual > 0.0:
        return None

    while upper - lower > 1:
        middle = lower + (upper - lower) // 2
        middle_residual = _knot_light_cone_residual_mm(
            source,
            middle,
            observer_time_ns=observer_time_ns,
            observer_position_mm=observer_position_mm,
        )
        if middle_residual >= 0.0:
            lower = middle
        else:
            upper = middle
    return lower


def _solve_retarded_sample(
    source: _PreparedSourceHistory,
    *,
    observer_time_ns: float,
    observer_position_mm: np.ndarray,
    root_tolerance_mm: float,
    max_root_iterations: int,
) -> _RetardedSample | None:
    times = source.time_ns
    segment = _find_retarded_knot_bracket(
        source,
        observer_time_ns=observer_time_ns,
        observer_position_mm=observer_position_mm,
    )
    if segment is None:
        return None
    lower_time = float(times[segment])
    upper_time = float(times[segment + 1])
    source_position = source.position_mm[segment]
    trial_time = 0.5 * (lower_time + upper_time)

    for _ in range(max_root_iterations):
        source_position, source_beta, source_beta_prime = _quintic_worldline_sample(
            source, segment, trial_time
        )
        residual, separation = _light_cone_residual_mm(
            observer_time_ns=observer_time_ns,
            observer_position_mm=observer_position_mm,
            source_time_ns=trial_time,
            source_position_mm=source_position,
        )
        if abs(residual) <= root_tolerance_mm:
            lower_time = upper_time = trial_time
            break
        if residual > 0.0:
            lower_time = trial_time
        else:
            upper_time = trial_time
        if np.nextafter(lower_time, upper_time) >= upper_time:
            break

        derivative = float("nan")
        if separation > 0.0:
            direction = (observer_position_mm - source_position) / separation
            derivative = -C_MMNS * (1.0 - float(direction @ source_beta))
        decision = _next_safeguarded_root_trial(
            trial_time_ns=trial_time,
            residual_mm=residual,
            derivative_mm_per_ns=derivative,
            lower_time_ns=lower_time,
            upper_time_ns=upper_time,
        )
        trial_time = decision.time_ns

    retarded_time = 0.5 * (lower_time + upper_time)
    source_position, source_beta, source_beta_prime = _quintic_worldline_sample(
        source, segment, retarded_time
    )
    residual, separation = _light_cone_residual_mm(
        observer_time_ns=observer_time_ns,
        observer_position_mm=observer_position_mm,
        source_time_ns=retarded_time,
        source_position_mm=source_position,
    )
    return _RetardedSample(
        time_ns=retarded_time,
        position_mm=source_position,
        beta=source_beta,
        beta_prime_per_mm=source_beta_prime,
        residual_mm=residual,
        separation_mm=separation,
    )


def _source_terminated_before_light_cone(
    source: _PreparedSourceHistory,
    *,
    observer_time_ns: float,
    observer_position_mm: np.ndarray,
) -> bool:
    """Return true when a lost source ended before the required emission event."""

    if not source.ended_by_loss:
        return False
    if source.time_ns.size == 0:
        return True
    last_alive = source.time_ns.size - 1
    residual, _ = _light_cone_residual_mm(
        observer_time_ns=observer_time_ns,
        observer_position_mm=observer_position_mm,
        source_time_ns=float(source.time_ns[last_alive]),
        source_position_mm=source.position_mm[last_alive],
    )
    # g(t_source) decreases monotonically for a timelike worldline. Positive
    # g at the final alive state means the required retarded emission would
    # occur only after the source was removed from the simulation.
    return residual > 0.0


def lienard_wiechert_charge_field_native(
    *,
    charge_native: float,
    separation_vector_mm: Sequence[float],
    source_beta: Sequence[float],
    source_beta_prime_per_mm: Sequence[float],
) -> tuple[np.ndarray, np.ndarray]:
    """Return native scaled-Gaussian ``(E, B)`` for one retarded charge.

    ``source_beta_prime_per_mm`` is ``d beta / d(c t)``. The radiation term
    therefore has no additional factor of ``c``.
    """

    charge = float(charge_native)
    separation_vector = np.asarray(separation_vector_mm, dtype=float)
    beta = np.asarray(source_beta, dtype=float)
    beta_prime = np.asarray(source_beta_prime_per_mm, dtype=float)
    if not np.isfinite(charge):
        raise ValueError("charge_native must be finite")
    for name, vector in (
        ("separation_vector_mm", separation_vector),
        ("source_beta", beta),
        ("source_beta_prime_per_mm", beta_prime),
    ):
        if vector.shape != (3,) or not np.all(np.isfinite(vector)):
            raise ValueError(f"{name} must contain three finite values")
    separation = float(np.linalg.norm(separation_vector))
    if separation <= 0.0:
        raise ValueError("the observer cannot coincide with a point-charge source")
    beta_squared = float(beta @ beta)
    if beta_squared >= 1.0:
        raise ValueError("source beta magnitude must be less than one")
    direction = separation_vector / separation
    kappa = 1.0 - float(direction @ beta)
    if kappa <= 1.0e-14:
        raise ValueError("retarded field is singular because 1 - n.beta is too small")

    velocity_field = (
        (1.0 - beta_squared) * (direction - beta) / (kappa**3 * separation**2)
    )
    radiation_field = np.cross(
        direction,
        np.cross(direction - beta, beta_prime),
    ) / (kappa**3 * separation)
    electric = charge * (velocity_field + radiation_field)
    magnetic = np.cross(direction, electric)
    return cast(tuple[np.ndarray, np.ndarray], (electric, magnetic))


def lienard_wiechert_charge_potential_native(
    *,
    charge_native: float,
    separation_vector_mm: Sequence[float],
    source_beta: Sequence[float],
) -> np.ndarray:
    """Return the native Gaussian retarded four-potential of one charge.

    With ``R`` and ``n`` evaluated at the retarded source event, the potential
    is

    ``A^mu = (phi, phi beta)``, ``phi = q / ((1 - n.beta) R)``.

    The returned potential is contravariant and uses ``x=(ct,x,y,z)``.  Its
    ordinary charge contribution to canonical momentum is therefore
    ``(q_observer/c) A^mu``.
    """

    charge = float(charge_native)
    separation_vector = np.asarray(separation_vector_mm, dtype=float)
    beta = np.asarray(source_beta, dtype=float)
    if not np.isfinite(charge):
        raise ValueError("charge_native must be finite")
    for name, vector in (
        ("separation_vector_mm", separation_vector),
        ("source_beta", beta),
    ):
        if vector.shape != (3,) or not np.all(np.isfinite(vector)):
            raise ValueError(f"{name} must contain three finite values")
    separation = float(np.linalg.norm(separation_vector))
    if separation <= 0.0:
        raise ValueError("the observer cannot coincide with a point-charge source")
    beta_squared = float(beta @ beta)
    if beta_squared >= 1.0:
        raise ValueError("source beta magnitude must be less than one")
    direction = separation_vector / separation
    kappa = 1.0 - float(direction @ beta)
    if kappa <= 1.0e-14:
        raise ValueError("retarded field is singular because 1 - n.beta is too small")

    scalar_potential = charge / (kappa * separation)
    return cast(
        np.ndarray,
        scalar_potential * np.concatenate((np.ones(1, dtype=float), beta)),
    )


def _validated_root_options(
    root_tolerance_mm: float, max_root_iterations: int
) -> tuple[float, int]:
    tolerance = float(root_tolerance_mm)
    iterations = int(max_root_iterations)
    if not np.isfinite(tolerance) or tolerance <= 0.0:
        raise ValueError("root_tolerance_mm must be finite and positive")
    if iterations <= 0:
        raise ValueError("max_root_iterations must be positive")
    return tolerance, iterations


def _evaluate_prepared_charge_field_native(
    prepared: _PreparedHistory,
    observer_event: ObserverEvent,
    *,
    require_complete_history: bool,
    root_tolerance_mm: float,
    max_root_iterations: int,
) -> RetardedChargeFieldResult:
    """Evaluate one event without extracting or preparing its history again."""

    arrays = prepared.arrays
    observer_time_ns = float(observer_event.time_ns)
    observer_position_mm = np.asarray(observer_event.position_mm, dtype=float)
    electric_total = np.zeros(3, dtype=float)
    magnetic_total = np.zeros(3, dtype=float)
    four_potential_total = np.zeros(4, dtype=float)
    retarded_time_ns = np.full(arrays.n_sources, np.nan, dtype=float)
    residual_mm = np.full(arrays.n_sources, np.nan, dtype=float)
    separation_mm = np.full(arrays.n_sources, np.nan, dtype=float)
    valid_sources = np.zeros(arrays.n_sources, dtype=bool)
    missing_sources: list[int] = []

    for source_index, source in prepared.sources.items():
        sample = _solve_retarded_sample(
            source,
            observer_time_ns=observer_time_ns,
            observer_position_mm=observer_position_mm,
            root_tolerance_mm=root_tolerance_mm,
            max_root_iterations=max_root_iterations,
        )
        if sample is None:
            if _source_terminated_before_light_cone(
                source,
                observer_time_ns=observer_time_ns,
                observer_position_mm=observer_position_mm,
            ):
                continue
            missing_sources.append(source_index)
            continue
        electric, magnetic = lienard_wiechert_charge_field_native(
            charge_native=float(arrays.charge_native[source_index]),
            separation_vector_mm=observer_position_mm - sample.position_mm,
            source_beta=tuple(float(value) for value in sample.beta),
            source_beta_prime_per_mm=tuple(
                float(value) for value in sample.beta_prime_per_mm
            ),
        )
        four_potential = lienard_wiechert_charge_potential_native(
            charge_native=float(arrays.charge_native[source_index]),
            separation_vector_mm=observer_position_mm - sample.position_mm,
            source_beta=tuple(float(value) for value in sample.beta),
        )
        electric_total += electric
        magnetic_total += magnetic
        four_potential_total += four_potential
        retarded_time_ns[source_index] = sample.time_ns
        residual_mm[source_index] = sample.residual_mm
        separation_mm[source_index] = sample.separation_mm
        valid_sources[source_index] = True

    if require_complete_history and missing_sources:
        raise RetardedHistoryError(
            "source history does not bracket the observer light cone for source "
            f"indices {missing_sources}"
        )
    field_tensor = electromagnetic_field_tensor_native(
        tuple(float(value) for value in electric_total),
        tuple(float(value) for value in magnetic_total),
    )
    return RetardedChargeFieldResult(
        electric_field_native=electric_total,
        magnetic_field_native=magnetic_total,
        field_tensor=field_tensor,
        retarded_time_ns=retarded_time_ns,
        light_cone_residual_mm=residual_mm,
        separation_mm=separation_mm,
        valid_sources=valid_sources,
        four_potential=four_potential_total,
    )


def _charge_batch_event_arrays(
    observer_events: Sequence[ObserverEvent],
) -> tuple[np.ndarray, np.ndarray]:
    event_count = len(observer_events)
    event_time_ns = np.asarray(
        [float(event.time_ns) for event in observer_events], dtype=float
    )
    event_position_mm = np.asarray(
        [
            tuple(float(value) for value in event.position_mm)
            for event in observer_events
        ],
        dtype=float,
    )
    if event_position_mm.shape != (event_count, 3):
        raise ValueError("retarded charge observer events must have shape [events, 3]")
    return event_time_ns, event_position_mm


def _evaluate_prepared_charge_batch_numba_roots_exact_serial(
    prepared: _PreparedHistory,
    observer_events: Sequence[ObserverEvent],
    *,
    require_complete_history: bool,
    root_tolerance_mm: float,
    max_root_iterations: int,
) -> tuple[RetardedChargeFieldResult, ...]:
    """Compile roots while retaining exact Python field and reduction order."""

    from .exact_retarded_numba import (
        NUMBA_COMPILATION_ERRORS,
        _STATUS_MISSING_HISTORY,
        _STATUS_TERMINATED_SOURCE,
        _STATUS_VALID,
        evaluate_source_roots_exact_serial,
    )

    event_time_ns, event_position_mm = _charge_batch_event_arrays(observer_events)
    source_batches: dict[int, tuple[np.ndarray, ...]] = {}
    for source_index, source in prepared.sources.items():
        compiling_initial_signature = not bool(
            getattr(evaluate_source_roots_exact_serial, "signatures", ())
        )
        try:
            source_batches[source_index] = cast(
                tuple[np.ndarray, ...],
                evaluate_source_roots_exact_serial(
                    source.time_ns,
                    source.position_mm,
                    source.segment_duration_ns,
                    source.position_coefficients_mm,
                    bool(source.ended_by_loss),
                    event_time_ns,
                    event_position_mm,
                    float(root_tolerance_mm),
                    int(max_root_iterations),
                ),
            )
        except NUMBA_COMPILATION_ERRORS as exc:
            if compiling_initial_signature:
                from .exact_retarded_backend import (
                    ExactRetardedBackendUnavailableError,
                )

                raise ExactRetardedBackendUnavailableError(
                    "exact retarded backend 'numba_roots_exact_serial' failed "
                    "during initial JIT compilation; select backend 'python' or "
                    "inspect the chained Numba error"
                ) from exc
            raise

    results: list[RetardedChargeFieldResult] = []
    arrays = prepared.arrays
    for event_index in range(len(observer_events)):
        electric_total = np.zeros(3, dtype=float)
        magnetic_total = np.zeros(3, dtype=float)
        potential_total = np.zeros(4, dtype=float)
        retarded_time_ns = np.full(arrays.n_sources, np.nan, dtype=float)
        residual_mm = np.full(arrays.n_sources, np.nan, dtype=float)
        separation_mm = np.full(arrays.n_sources, np.nan, dtype=float)
        valid_sources = np.zeros(arrays.n_sources, dtype=bool)
        missing_sources: list[int] = []

        for source_index, source in prepared.sources.items():
            batch = source_batches[source_index]
            status = int(batch[0][event_index])
            if status == _STATUS_TERMINATED_SOURCE:
                continue
            if status == _STATUS_MISSING_HISTORY:
                missing_sources.append(source_index)
                continue
            if status != _STATUS_VALID:
                raise RuntimeError(f"unknown retarded charge root status {status}")

            source_time_ns = float(batch[2][event_index])
            segment_index = int(
                np.searchsorted(source.time_ns, source_time_ns, side="right") - 1
            )
            segment_index = min(max(segment_index, 0), int(source.time_ns.size) - 2)
            source_position_mm, source_beta, source_beta_prime = (
                _quintic_worldline_sample(source, segment_index, source_time_ns)
            )
            source_residual_mm, source_separation_mm = _light_cone_residual_mm(
                observer_time_ns=float(event_time_ns[event_index]),
                observer_position_mm=event_position_mm[event_index],
                source_time_ns=source_time_ns,
                source_position_mm=source_position_mm,
            )
            electric, magnetic = lienard_wiechert_charge_field_native(
                charge_native=float(arrays.charge_native[source_index]),
                separation_vector_mm=(
                    event_position_mm[event_index] - source_position_mm
                ),
                source_beta=cast(Sequence[float], source_beta),
                source_beta_prime_per_mm=cast(Sequence[float], source_beta_prime),
            )
            potential = lienard_wiechert_charge_potential_native(
                charge_native=float(arrays.charge_native[source_index]),
                separation_vector_mm=(
                    event_position_mm[event_index] - source_position_mm
                ),
                source_beta=cast(Sequence[float], source_beta),
            )
            electric_total += electric
            magnetic_total += magnetic
            potential_total += potential
            retarded_time_ns[source_index] = source_time_ns
            residual_mm[source_index] = source_residual_mm
            separation_mm[source_index] = source_separation_mm
            valid_sources[source_index] = True

        if require_complete_history and missing_sources:
            raise RetardedHistoryError(
                "source history does not bracket the observer light cone for source "
                f"indices {missing_sources}"
            )
        results.append(
            RetardedChargeFieldResult(
                electric_field_native=electric_total,
                magnetic_field_native=magnetic_total,
                field_tensor=electromagnetic_field_tensor_native(
                    tuple(float(value) for value in electric_total),
                    tuple(float(value) for value in magnetic_total),
                ),
                retarded_time_ns=retarded_time_ns,
                light_cone_residual_mm=residual_mm,
                separation_mm=separation_mm,
                valid_sources=valid_sources,
                four_potential=potential_total,
            )
        )
    return tuple(results)


def _evaluate_prepared_charge_batch_numba_full_strict_serial(
    prepared: _PreparedHistory,
    observer_events: Sequence[ObserverEvent],
    *,
    require_complete_history: bool,
    root_tolerance_mm: float,
    max_root_iterations: int,
) -> tuple[RetardedChargeFieldResult, ...]:
    """Compile complete source events while retaining reference reductions."""

    from .exact_retarded_numba import (
        NUMBA_COMPILATION_ERRORS,
        _STATUS_CHARGE_SINGULAR_KAPPA,
        _STATUS_CHARGE_SUPERLUMINAL_SOURCE,
        _STATUS_CHARGE_ZERO_SEPARATION,
        _STATUS_MISSING_HISTORY,
        _STATUS_TERMINATED_SOURCE,
        _STATUS_VALID,
        evaluate_charge_source_events_full_strict_serial,
    )

    event_time_ns, event_position_mm = _charge_batch_event_arrays(observer_events)
    source_batches: dict[int, tuple[np.ndarray, ...]] = {}
    for source_index, source in prepared.sources.items():
        compiling_initial_signature = not bool(
            getattr(
                evaluate_charge_source_events_full_strict_serial,
                "signatures",
                (),
            )
        )
        try:
            source_batches[source_index] = cast(
                tuple[np.ndarray, ...],
                evaluate_charge_source_events_full_strict_serial(
                    source.time_ns,
                    source.position_mm,
                    source.segment_duration_ns,
                    source.position_coefficients_mm,
                    float(prepared.arrays.charge_native[source_index]),
                    bool(source.ended_by_loss),
                    event_time_ns,
                    event_position_mm,
                    float(root_tolerance_mm),
                    int(max_root_iterations),
                ),
            )
        except NUMBA_COMPILATION_ERRORS as exc:
            if compiling_initial_signature:
                from .exact_retarded_backend import (
                    ExactRetardedBackendUnavailableError,
                )

                raise ExactRetardedBackendUnavailableError(
                    "exact retarded backend 'numba_full_strict_serial' failed "
                    "during initial JIT compilation; select backend 'python' or "
                    "inspect the chained Numba error"
                ) from exc
            raise

    results: list[RetardedChargeFieldResult] = []
    arrays = prepared.arrays
    for event_index in range(len(observer_events)):
        electric_total = np.zeros(3, dtype=float)
        magnetic_total = np.zeros(3, dtype=float)
        potential_total = np.zeros(4, dtype=float)
        retarded_time_ns = np.full(arrays.n_sources, np.nan, dtype=float)
        residual_mm = np.full(arrays.n_sources, np.nan, dtype=float)
        separation_mm = np.full(arrays.n_sources, np.nan, dtype=float)
        valid_sources = np.zeros(arrays.n_sources, dtype=bool)
        missing_sources: list[int] = []

        for source_index, _source in prepared.sources.items():
            batch = source_batches[source_index]
            status = int(batch[0][event_index])
            if status == _STATUS_TERMINATED_SOURCE:
                continue
            if status == _STATUS_MISSING_HISTORY:
                missing_sources.append(source_index)
                continue
            if status == _STATUS_CHARGE_ZERO_SEPARATION:
                raise ValueError(
                    "the observer cannot coincide with a point-charge source"
                )
            if status == _STATUS_CHARGE_SUPERLUMINAL_SOURCE:
                raise ValueError("source beta magnitude must be less than one")
            if status == _STATUS_CHARGE_SINGULAR_KAPPA:
                raise ValueError(
                    "retarded field is singular because 1 - n.beta is too small"
                )
            if status != _STATUS_VALID:
                raise RuntimeError(f"unknown strict charge event status {status}")

            electric_total += batch[1][event_index]
            magnetic_total += batch[2][event_index]
            potential_total += batch[3][event_index]
            retarded_time_ns[source_index] = float(batch[4][event_index])
            residual_mm[source_index] = float(batch[5][event_index])
            separation_mm[source_index] = float(batch[6][event_index])
            valid_sources[source_index] = bool(batch[7][event_index])

        if require_complete_history and missing_sources:
            raise RetardedHistoryError(
                "source history does not bracket the observer light cone for source "
                f"indices {missing_sources}"
            )
        results.append(
            RetardedChargeFieldResult(
                electric_field_native=electric_total,
                magnetic_field_native=magnetic_total,
                field_tensor=electromagnetic_field_tensor_native(
                    tuple(float(value) for value in electric_total),
                    tuple(float(value) for value in magnetic_total),
                ),
                retarded_time_ns=retarded_time_ns,
                light_cone_residual_mm=residual_mm,
                separation_mm=separation_mm,
                valid_sources=valid_sources,
                four_potential=potential_total,
            )
        )
    return tuple(results)


def _evaluate_prepared_charge_batch(
    prepared: _PreparedHistory,
    observer_events: Sequence[ObserverEvent],
    *,
    backend: str,
    require_complete_history: bool,
    root_tolerance_mm: float,
    max_root_iterations: int,
) -> tuple[RetardedChargeFieldResult, ...]:
    if backend == "numba_roots_exact_serial":
        return _evaluate_prepared_charge_batch_numba_roots_exact_serial(
            prepared,
            observer_events,
            require_complete_history=require_complete_history,
            root_tolerance_mm=root_tolerance_mm,
            max_root_iterations=max_root_iterations,
        )
    if backend in {
        "numba_full_strict_serial",
        "numba_analytic_charge_response_serial",
        "numba_analytic_charge_dipole_response_serial",
        "metal_certified_full_strict",
    }:
        return _evaluate_prepared_charge_batch_numba_full_strict_serial(
            prepared,
            observer_events,
            require_complete_history=require_complete_history,
            root_tolerance_mm=root_tolerance_mm,
            max_root_iterations=max_root_iterations,
        )
    return tuple(
        _evaluate_prepared_charge_field_native(
            prepared,
            event,
            require_complete_history=require_complete_history,
            root_tolerance_mm=root_tolerance_mm,
            max_root_iterations=max_root_iterations,
        )
        for event in observer_events
    )


def _segment_beta_bernstein_bound(
    source: _PreparedSourceHistory,
    segment_index: int,
) -> float:
    """Return a rigorous speed bound for one quintic worldline segment.

    The segment velocity is a degree-four polynomial.  Expressing it in the
    Bernstein basis puts the complete vector curve inside the convex hull of
    its five control points, so the largest control-point norm bounds
    ``|beta|`` everywhere on the segment.
    """

    segment = int(segment_index)
    duration_coordinate = C_MMNS * float(source.segment_duration_ns[segment])
    coefficients = np.asarray(source.position_coefficients_mm[segment], dtype=float)
    power = np.empty((5, 3), dtype=float)
    for order in range(5):
        power[order] = (order + 1) * coefficients[order + 1] / duration_coordinate
    bernstein = np.zeros((5, 3), dtype=float)
    degree = 4
    for control in range(5):
        for order in range(control + 1):
            bernstein[control] += (
                comb(control, order) / comb(degree, order) * power[order]
            )
    return float(np.max(np.linalg.norm(bernstein, axis=1)))


def _analytical_segment_margin_ratio(
    *,
    source: _PreparedSourceHistory,
    segment_index: int,
    retarded_time_ns: float,
    observer_stencil_step_mm: float,
) -> tuple[float, str | None]:
    """Prove whether a centered observer stencil can remain in one segment.

    For a source with ``|beta| <= beta_bound < 1``, implicit differentiation
    of the light-cone equation gives
    ``|d(ct_ret)/d x_observer^lambda| <= 1/(1-beta_bound)``.  A retarded root
    farther than ``step/(1-beta_bound)`` from both segment boundaries therefore
    cannot cross either boundary under any one-coordinate stencil displacement.
    """

    beta_bound = _segment_beta_bernstein_bound(source, segment_index)
    if not np.isfinite(beta_bound) or beta_bound >= 1.0:
        return 0.0, "segment_velocity_bound_is_not_timelike"
    segment_start = float(source.time_ns[segment_index])
    segment_end = float(source.time_ns[segment_index + 1])
    root = float(retarded_time_ns)
    coordinate_margin = C_MMNS * min(root - segment_start, segment_end - root)
    maximum_root_shift = float(observer_stencil_step_mm) / (1.0 - beta_bound)
    if not np.isfinite(coordinate_margin) or coordinate_margin <= 0.0:
        return 0.0, "retarded_root_is_on_segment_boundary"
    ratio = coordinate_margin / maximum_root_shift
    if not np.isfinite(ratio) or ratio <= 1.0:
        return float(ratio), "retarded_root_near_segment_boundary"
    return float(ratio), None


def _response_gradient_from_maintained_stencil(
    history: TrajectoryHistory,
    observer_event: ObserverEvent,
    *,
    excluded_source_indices: Sequence[int],
    require_complete_history: bool,
    relative_step: float,
    minimum_step_mm: float,
    root_tolerance_mm: float,
    max_root_iterations: int,
    backend: str,
    fallback_reason: str,
    kappa: np.ndarray,
    segment_index: np.ndarray,
    minimum_segment_margin_ratio: float,
) -> RetardedChargeResponseGradientResult:
    from .antisymmetric_response_rfs import (
        pack_antisymmetric_response_native,
        pack_partial_antisymmetric_response_native,
    )

    fallback = evaluate_retarded_charge_field_gradient_native(
        history,
        observer_event,
        excluded_source_indices=excluded_source_indices,
        require_complete_history=require_complete_history,
        relative_step=relative_step,
        minimum_step_mm=minimum_step_mm,
        root_tolerance_mm=root_tolerance_mm,
        max_root_iterations=max_root_iterations,
        backend=backend,
    )
    return RetardedChargeResponseGradientResult(
        four_potential=fallback.field.four_potential,
        partial_a=fallback.partial_a,
        antisymmetric_response=pack_antisymmetric_response_native(
            fallback.field.field_tensor
        ),
        partial_antisymmetric_response=(
            pack_partial_antisymmetric_response_native(fallback.partial_f)
        ),
        retarded_time_ns=fallback.field.retarded_time_ns,
        light_cone_residual_mm=fallback.field.light_cone_residual_mm,
        separation_mm=fallback.field.separation_mm,
        valid_sources=fallback.field.valid_sources,
        kappa=kappa,
        segment_index=segment_index,
        minimum_segment_margin_ratio=minimum_segment_margin_ratio,
        fallback_used=True,
        fallback_reason=fallback_reason,
        fallback_stencil_step_mm=float(fallback.stencil_step_mm),
    )


def evaluate_retarded_charge_response_gradient_native(
    history: TrajectoryHistory,
    observer_event: ObserverEvent,
    *,
    excluded_source_indices: Sequence[int] = (),
    require_complete_history: bool = True,
    relative_step: float = _DEFAULT_GRADIENT_RELATIVE_STEP,
    minimum_step_mm: float = _DEFAULT_GRADIENT_MINIMUM_STEP_MM,
    root_tolerance_mm: float = _DEFAULT_ROOT_TOLERANCE_MM,
    max_root_iterations: int = _DEFAULT_MAX_ROOT_ITERATIONS,
    fallback_backend: str = "numba_full_strict_serial",
) -> RetardedChargeResponseGradientResult:
    """Evaluate one-root analytical charge response coefficients.

    The result follows the maintained source-addition and error ordering.  It
    falls back to the centered-stencil provider only when a rigorous segment
    speed/margin bound cannot prove that the analytical derivative stays on
    the same smooth quintic segment.
    """

    require_exact_retarded_backend("numba_analytic_charge_response_serial")
    from .charge_response_jet_numba import (
        _STATUS_CHARGE_SINGULAR_KAPPA,
        _STATUS_CHARGE_SUPERLUMINAL_SOURCE,
        _STATUS_CHARGE_ZERO_SEPARATION,
        evaluate_charge_response_coefficients_one_event_strict_serial,
    )
    from .exact_retarded_numba import (
        NUMBA_COMPILATION_ERRORS,
        _STATUS_MISSING_HISTORY,
        _STATUS_TERMINATED_SOURCE,
        _STATUS_VALID,
    )

    selected_fallback = require_exact_retarded_backend(fallback_backend)
    if selected_fallback in {
        "numba_analytic_charge_response_serial",
        "numba_analytic_charge_dipole_response_serial",
    }:
        raise ValueError("analytical charge-response fallback cannot select itself")
    relative = float(relative_step)
    minimum = float(minimum_step_mm)
    if not np.isfinite(relative) or relative <= 0.0 or relative >= 0.1:
        raise ValueError("relative_step must be finite and in (0, 0.1)")
    if not np.isfinite(minimum) or minimum <= 0.0:
        raise ValueError("minimum_step_mm must be finite and positive")
    tolerance, iterations = _validated_root_options(
        root_tolerance_mm, max_root_iterations
    )
    prepared = _prepare_history(history, excluded_source_indices)
    arrays = prepared.arrays
    potential_total = np.zeros(4, dtype=float)
    partial_a_total = np.zeros((4, 4), dtype=float)
    response_total = np.zeros(6, dtype=float)
    partial_response_total = np.zeros((4, 6), dtype=float)
    retarded_time_ns = np.full(arrays.n_sources, np.nan, dtype=float)
    residual_mm = np.full(arrays.n_sources, np.nan, dtype=float)
    separation_mm = np.full(arrays.n_sources, np.nan, dtype=float)
    valid_sources = np.zeros(arrays.n_sources, dtype=bool)
    kappa = np.full(arrays.n_sources, np.nan, dtype=float)
    segment_index = np.full(arrays.n_sources, -1, dtype=int)
    missing_sources: list[int] = []

    compiling_initial_signature = not bool(
        getattr(
            evaluate_charge_response_coefficients_one_event_strict_serial,
            "signatures",
            (),
        )
    )
    for source_index, source in prepared.sources.items():
        try:
            result = evaluate_charge_response_coefficients_one_event_strict_serial(
                source.time_ns,
                source.position_mm,
                source.segment_duration_ns,
                source.position_coefficients_mm,
                float(arrays.charge_native[source_index]),
                bool(source.ended_by_loss),
                float(observer_event.time_ns),
                np.asarray(observer_event.position_mm, dtype=float),
                tolerance,
                iterations,
            )
        except NUMBA_COMPILATION_ERRORS as exc:
            if compiling_initial_signature:
                from .exact_retarded_backend import (
                    ExactRetardedBackendUnavailableError,
                )

                raise ExactRetardedBackendUnavailableError(
                    "exact retarded backend "
                    "'numba_analytic_charge_response_serial' failed during "
                    "initial JIT compilation; select backend "
                    "'numba_full_strict_serial' or inspect the chained Numba error"
                ) from exc
            raise
        status = int(result[0])
        if status == _STATUS_TERMINATED_SOURCE:
            continue
        if status == _STATUS_MISSING_HISTORY:
            missing_sources.append(source_index)
            continue
        if status == _STATUS_CHARGE_ZERO_SEPARATION:
            raise ValueError("the observer cannot coincide with a point-charge source")
        if status == _STATUS_CHARGE_SUPERLUMINAL_SOURCE:
            raise ValueError("source beta magnitude must be less than one")
        if status == _STATUS_CHARGE_SINGULAR_KAPPA:
            raise ValueError(
                "retarded field is singular because 1 - n.beta is too small"
            )
        if status != _STATUS_VALID:
            raise RuntimeError(f"unknown analytical charge response status {status}")
        potential_total += result[1]
        partial_a_total += result[2]
        response_total += result[3]
        partial_response_total += result[4]
        kappa[source_index] = float(result[5])
        retarded_time_ns[source_index] = float(result[6])
        residual_mm[source_index] = float(result[7])
        separation_mm[source_index] = float(result[8])
        segment_index[source_index] = int(result[9])
        valid_sources[source_index] = True

    if require_complete_history and missing_sources:
        raise RetardedHistoryError(
            "source history does not bracket the observer light cone for source "
            f"indices {missing_sources}"
        )
    finite_separations = separation_mm[valid_sources]
    stencil_step = (
        minimum
        if finite_separations.size == 0
        else max(minimum, relative * float(np.min(finite_separations)))
    )
    minimum_margin_ratio = float("inf")
    fallback_reason: str | None = None
    for source_index, source in prepared.sources.items():
        if not valid_sources[source_index]:
            continue
        margin_ratio, reason = _analytical_segment_margin_ratio(
            source=source,
            segment_index=int(segment_index[source_index]),
            retarded_time_ns=float(retarded_time_ns[source_index]),
            observer_stencil_step_mm=stencil_step,
        )
        minimum_margin_ratio = min(minimum_margin_ratio, margin_ratio)
        if reason is not None and fallback_reason is None:
            fallback_reason = f"source_{source_index}:{reason}"
    if not all(
        np.all(np.isfinite(value))
        for value in (
            potential_total,
            partial_a_total,
            response_total,
            partial_response_total,
        )
    ):
        fallback_reason = fallback_reason or "nonfinite_analytical_response"
    from .analytic_charge_response_diagnostics import (
        record_analytic_charge_response,
    )

    record_analytic_charge_response(
        valid_sources=int(np.count_nonzero(valid_sources)),
        minimum_segment_margin_ratio=minimum_margin_ratio,
        fallback_reason=fallback_reason,
    )
    if fallback_reason is not None:
        return _response_gradient_from_maintained_stencil(
            history,
            observer_event,
            excluded_source_indices=excluded_source_indices,
            require_complete_history=require_complete_history,
            relative_step=relative,
            minimum_step_mm=minimum,
            root_tolerance_mm=tolerance,
            max_root_iterations=iterations,
            backend=selected_fallback,
            fallback_reason=fallback_reason,
            kappa=kappa,
            segment_index=segment_index,
            minimum_segment_margin_ratio=minimum_margin_ratio,
        )
    return RetardedChargeResponseGradientResult(
        four_potential=potential_total,
        partial_a=partial_a_total,
        antisymmetric_response=response_total,
        partial_antisymmetric_response=partial_response_total,
        retarded_time_ns=retarded_time_ns,
        light_cone_residual_mm=residual_mm,
        separation_mm=separation_mm,
        valid_sources=valid_sources,
        kappa=kappa,
        segment_index=segment_index,
        minimum_segment_margin_ratio=minimum_margin_ratio,
        fallback_used=False,
        fallback_reason=None,
        fallback_stencil_step_mm=None,
    )


def evaluate_retarded_charge_field_native(
    history: TrajectoryHistory,
    observer_event: ObserverEvent,
    *,
    excluded_source_indices: Sequence[int] = (),
    require_complete_history: bool = True,
    root_tolerance_mm: float = _DEFAULT_ROOT_TOLERANCE_MM,
    max_root_iterations: int = _DEFAULT_MAX_ROOT_ITERATIONS,
    backend: str = "python",
) -> RetardedChargeFieldResult:
    """Evaluate the summed native Gaussian charge field at one event."""

    selected_backend = require_exact_retarded_backend(backend)
    tolerance, iterations = _validated_root_options(
        root_tolerance_mm, max_root_iterations
    )
    prepared = _prepare_history(history, excluded_source_indices)
    return _evaluate_prepared_charge_batch(
        prepared,
        (observer_event,),
        backend=selected_backend,
        require_complete_history=require_complete_history,
        root_tolerance_mm=tolerance,
        max_root_iterations=iterations,
    )[0]


def evaluate_retarded_charge_field_gradient_native(
    history: TrajectoryHistory,
    observer_event: ObserverEvent,
    *,
    excluded_source_indices: Sequence[int] = (),
    require_complete_history: bool = True,
    relative_step: float = _DEFAULT_GRADIENT_RELATIVE_STEP,
    minimum_step_mm: float = _DEFAULT_GRADIENT_MINIMUM_STEP_MM,
    root_tolerance_mm: float = _DEFAULT_ROOT_TOLERANCE_MM,
    max_root_iterations: int = _DEFAULT_MAX_ROOT_ITERATIONS,
    backend: str = "python",
) -> RetardedChargeFieldGradientResult:
    """Evaluate F and its complete centered spacetime derivative.

    partial_f[lambda, mu, nu] is partial_lambda F^(mu nu) for
    x=(ct,x,y,z) in millimetres. Every displaced event independently re-solves
    every source light cone.
    """

    selected_backend = require_exact_retarded_backend(backend)
    relative = float(relative_step)
    minimum = float(minimum_step_mm)
    if not np.isfinite(relative) or relative <= 0.0 or relative >= 0.1:
        raise ValueError("relative_step must be finite and in (0, 0.1)")
    if not np.isfinite(minimum) or minimum <= 0.0:
        raise ValueError("minimum_step_mm must be finite and positive")
    tolerance, iterations = _validated_root_options(
        root_tolerance_mm, max_root_iterations
    )
    if selected_backend in {
        "numba_analytic_charge_response_serial",
        "numba_analytic_charge_dipole_response_serial",
    }:
        from .antisymmetric_response_rfs import (
            materialize_antisymmetric_response_native,
            materialize_partial_antisymmetric_response_native,
        )

        response = evaluate_retarded_charge_response_gradient_native(
            history,
            observer_event,
            excluded_source_indices=excluded_source_indices,
            require_complete_history=require_complete_history,
            relative_step=relative,
            minimum_step_mm=minimum,
            root_tolerance_mm=tolerance,
            max_root_iterations=iterations,
        )
        packed = response.antisymmetric_response
        field_tensor = materialize_antisymmetric_response_native(packed)
        return RetardedChargeFieldGradientResult(
            field=RetardedChargeFieldResult(
                electric_field_native=-packed[:3],
                magnetic_field_native=np.asarray(
                    (-packed[5], packed[4], -packed[3]), dtype=float
                ),
                field_tensor=field_tensor,
                retarded_time_ns=response.retarded_time_ns,
                light_cone_residual_mm=response.light_cone_residual_mm,
                separation_mm=response.separation_mm,
                valid_sources=response.valid_sources,
                four_potential=response.four_potential,
            ),
            partial_f=materialize_partial_antisymmetric_response_native(
                response.partial_antisymmetric_response
            ),
            stencil_step_mm=(
                float(response.fallback_stencil_step_mm)
                if response.fallback_stencil_step_mm is not None
                else 0.0
            ),
            stencil_retarded_time_ns=np.full(
                (4, 2, response.retarded_time_ns.size), np.nan, dtype=float
            ),
            partial_a=response.partial_a,
        )
    prepared = _prepare_history(history, excluded_source_indices)
    center = _evaluate_prepared_charge_field_native(
        prepared,
        observer_event,
        require_complete_history=require_complete_history,
        root_tolerance_mm=tolerance,
        max_root_iterations=iterations,
    )
    finite_separations = center.separation_mm[center.valid_sources]
    if finite_separations.size == 0:
        stencil_step = minimum
    else:
        stencil_step = max(minimum, relative * float(np.min(finite_separations)))

    partial_f = np.zeros((4, 4, 4), dtype=float)
    partial_a = np.zeros((4, 4), dtype=float)
    retarded_times = np.full((4, 2, center.retarded_time_ns.size), np.nan, dtype=float)
    center_position = np.asarray(observer_event.position_mm, dtype=float)
    displaced_events: list[ObserverEvent] = []
    for derivative_index in range(4):
        for sign in (-1.0, 1.0):
            if derivative_index == 0:
                displaced = ObserverEvent(
                    time_ns=(
                        float(observer_event.time_ns) + sign * stencil_step / C_MMNS
                    ),
                    position_mm=observer_event.position_mm,
                )
            else:
                displaced_position = center_position.copy()
                displaced_position[derivative_index - 1] += sign * stencil_step
                displaced_position_tuple = cast(
                    tuple[float, float, float],
                    tuple(float(value) for value in displaced_position),
                )
                displaced = ObserverEvent(
                    time_ns=float(observer_event.time_ns),
                    position_mm=displaced_position_tuple,
                )
            displaced_events.append(displaced)

    displaced_fields = _evaluate_prepared_charge_batch(
        prepared,
        displaced_events,
        backend=selected_backend,
        require_complete_history=require_complete_history,
        root_tolerance_mm=tolerance,
        max_root_iterations=iterations,
    )
    for derivative_index in range(4):
        lower = displaced_fields[2 * derivative_index]
        upper = displaced_fields[2 * derivative_index + 1]
        retarded_times[derivative_index, 0] = lower.retarded_time_ns
        retarded_times[derivative_index, 1] = upper.retarded_time_ns
        partial_f[derivative_index] = (upper.field_tensor - lower.field_tensor) / (
            2.0 * stencil_step
        )
        partial_a[derivative_index] = (upper.four_potential - lower.four_potential) / (
            2.0 * stencil_step
        )

    return RetardedChargeFieldGradientResult(
        field=center,
        partial_f=partial_f,
        stencil_step_mm=stencil_step,
        stencil_retarded_time_ns=retarded_times,
        partial_a=partial_a,
    )


__all__ = [
    "ObserverEvent",
    "RetardedChargeFieldGradientResult",
    "RetardedChargeFieldResult",
    "RetardedChargeResponseGradientResult",
    "RetardedHistoryError",
    "evaluate_retarded_charge_field_gradient_native",
    "evaluate_retarded_charge_field_native",
    "evaluate_retarded_charge_response_gradient_native",
    "lienard_wiechert_charge_field_native",
    "lienard_wiechert_charge_potential_native",
]
