"""Observer-independent retarded fields generated by point charges.

This module supplies the electromagnetic field and its complete spacetime
gradient at an explicit observer event. It is intentionally independent of
the observer charge: neutral particles with an intrinsic magnetic moment must
see the same source field as charged particles.

Unlike the legacy chrono-matching force path, every evaluation here solves the
light-cone equation

    c (t_observer - t_source) = |x_observer - x_source(t_source)|

against an interpolated source worldline. A finite-difference gradient calls
that complete evaluator again at all eight displaced events, so the derivative
includes the retarded-time chain rule. Freezing a previously selected source
sample would not be a derivative of a Lienard--Wiechert field.

Only charge-generated fields are constructed. Intrinsic dipole source fields,
their singular self fields, and dipole radiation reaction are deliberately out
of scope for this layer.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence, cast

import numpy as np

from .constants import C_MMNS
from .rfs import electromagnetic_field_tensor_native
from .types import IndexedTrajectoryArrays, Trajectory, TrajectoryArrays

TrajectoryHistory = Trajectory | TrajectoryArrays | IndexedTrajectoryArrays

_DEFAULT_ROOT_TOLERANCE_MM = 1.0e-21
_DEFAULT_MAX_ROOT_ITERATIONS = 96
_DEFAULT_GRADIENT_RELATIVE_STEP = 1.0e-4
_DEFAULT_GRADIENT_MINIMUM_STEP_MM = 1.0e-15


class RetardedHistoryError(ValueError):
    """Raised when a source history does not bracket a retarded event."""


@dataclass(frozen=True)
class ObserverEvent:
    """One observer event in the solver's millimetre/nanosecond units."""

    time_ns: float
    position_mm: tuple[float, float, float]

    def __post_init__(self) -> None:
        time = float(self.time_ns)
        position = np.asarray(self.position_mm, dtype=float)
        if not np.isfinite(time):
            raise ValueError("observer time must be finite")
        if position.shape != (3,) or not np.all(np.isfinite(position)):
            raise ValueError("observer position must contain three finite values")


@dataclass(frozen=True)
class RetardedChargeFieldResult:
    """Total native Gaussian charge field and light-cone diagnostics."""

    electric_field_native: np.ndarray
    magnetic_field_native: np.ndarray
    field_tensor: np.ndarray
    retarded_time_ns: np.ndarray
    light_cone_residual_mm: np.ndarray
    separation_mm: np.ndarray
    valid_sources: np.ndarray


@dataclass(frozen=True)
class RetardedChargeFieldGradientResult:
    """A native charge field plus ``partial_lambda F^(mu nu)`` per mm."""

    field: RetardedChargeFieldResult
    partial_f: np.ndarray
    stencil_step_mm: float
    stencil_retarded_time_ns: np.ndarray


@dataclass(frozen=True)
class _HistoryArrays:
    time_ns: np.ndarray
    position_mm: np.ndarray
    beta: np.ndarray
    beta_prime_per_mm: np.ndarray
    charge_native: np.ndarray
    dead: np.ndarray

    @property
    def n_sources(self) -> int:
        return int(self.time_ns.shape[1])


@dataclass(frozen=True)
class _PreparedSourceHistory:
    """One alive source prefix with reusable quintic segment coefficients."""

    source_index: int
    time_ns: np.ndarray
    position_mm: np.ndarray
    beta: np.ndarray
    beta_prime_per_mm: np.ndarray
    segment_duration_ns: np.ndarray
    position_coefficients_mm: np.ndarray
    ended_by_loss: bool


@dataclass(frozen=True)
class _PreparedHistory:
    """Extracted history and the non-excluded charged source interpolants."""

    arrays: _HistoryArrays
    sources: dict[int, _PreparedSourceHistory]


@dataclass(frozen=True)
class _RetardedSample:
    time_ns: float
    position_mm: np.ndarray
    beta: np.ndarray
    beta_prime_per_mm: np.ndarray
    residual_mm: float
    separation_mm: float


@dataclass(frozen=True)
class _RootTrialDecision:
    """One safeguarded Newton step and how its bracket protection was used."""

    time_ns: float
    used_bisection: bool
    used_nextafter: bool


def _legacy_matrix(history: Trajectory, field_name: str) -> np.ndarray:
    return np.stack(
        [np.asarray(state[field_name], dtype=float) for state in history],
        axis=0,
    )


def _legacy_constant(history: Trajectory, field_name: str) -> np.ndarray:
    if not history:
        return np.zeros(0, dtype=float)
    return np.asarray(history[-1][field_name], dtype=float)


def _history_matrix(history: TrajectoryHistory, field_name: str) -> np.ndarray:
    if isinstance(history, IndexedTrajectoryArrays):
        start = int(history.start_step)
        values = np.asarray(getattr(history.base, field_name), dtype=float)[start:]
        return np.asarray(values[:, history.particle_indices], dtype=float)
    if isinstance(history, TrajectoryArrays):
        return np.asarray(getattr(history, field_name), dtype=float)
    return _legacy_matrix(history, field_name)


def _history_constant(history: TrajectoryHistory, field_name: str) -> np.ndarray:
    if isinstance(history, IndexedTrajectoryArrays):
        return np.asarray(history.constant(field_name), dtype=float)
    if isinstance(history, TrajectoryArrays):
        return np.asarray(getattr(history, field_name), dtype=float)
    return _legacy_constant(history, field_name)


def _history_dead(history: TrajectoryHistory, shape: tuple[int, int]) -> np.ndarray:
    if isinstance(history, IndexedTrajectoryArrays):
        start = int(history.start_step)
        dead = np.asarray(history.base.dead, dtype=bool)[start:]
        return np.asarray(dead[:, history.particle_indices], dtype=bool)
    if isinstance(history, TrajectoryArrays):
        return np.asarray(history.dead, dtype=bool)
    rows = [
        np.asarray(
            state.get("_dead_particles", np.zeros(shape[1], dtype=bool)),
            dtype=bool,
        )
        for state in history
    ]
    return np.stack(rows, axis=0) if rows else np.zeros(shape, dtype=bool)


def _source_charge_native(history: TrajectoryHistory) -> np.ndarray:
    for field_name in ("q_source", "q"):
        try:
            return _history_constant(history, field_name)
        except (AttributeError, KeyError):
            continue
    raise ValueError("source history must provide q_source or q")


def _extract_history(history: TrajectoryHistory) -> _HistoryArrays:
    if isinstance(history, list) and not history:
        return _HistoryArrays(
            time_ns=np.zeros((0, 0)),
            position_mm=np.zeros((0, 0, 3)),
            beta=np.zeros((0, 0, 3)),
            beta_prime_per_mm=np.zeros((0, 0, 3)),
            charge_native=np.zeros(0),
            dead=np.zeros((0, 0), dtype=bool),
        )

    time_ns = _history_matrix(history, "t")
    x_mm = _history_matrix(history, "x")
    y_mm = _history_matrix(history, "y")
    z_mm = _history_matrix(history, "z")
    bx = _history_matrix(history, "bx")
    by = _history_matrix(history, "by")
    bz = _history_matrix(history, "bz")
    bdotx = _history_matrix(history, "bdotx")
    bdoty = _history_matrix(history, "bdoty")
    bdotz = _history_matrix(history, "bdotz")
    matrices = (x_mm, y_mm, z_mm, bx, by, bz, bdotx, bdoty, bdotz)
    if time_ns.ndim != 2 or any(matrix.shape != time_ns.shape for matrix in matrices):
        raise ValueError("source history fields must share shape [steps, particles]")
    if not all(np.all(np.isfinite(matrix)) for matrix in (time_ns, *matrices)):
        raise ValueError("source history kinematics must be finite")

    charge_native = np.asarray(_source_charge_native(history), dtype=float)
    if charge_native.shape != (time_ns.shape[1],):
        raise ValueError("source charge array must match the particle count")
    if not np.all(np.isfinite(charge_native)):
        raise ValueError("source charge array must contain only finite values")
    position_mm = np.stack((x_mm, y_mm, z_mm), axis=-1)
    beta = np.stack((bx, by, bz), axis=-1)
    # Stored bdot is d beta / d(ct), where ct is measured in millimetres.
    beta_prime_per_mm = np.stack((bdotx, bdoty, bdotz), axis=-1)
    dead = _history_dead(history, time_ns.shape)
    return _HistoryArrays(
        time_ns=time_ns,
        position_mm=position_mm,
        beta=beta,
        beta_prime_per_mm=beta_prime_per_mm,
        charge_native=charge_native,
        dead=dead,
    )


def _quintic_worldline_sample(
    source: _PreparedSourceHistory,
    segment_index: int,
    time_ns: float,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Interpolate position, velocity, and acceleration continuously."""

    t0 = float(source.time_ns[segment_index])
    duration = float(source.segment_duration_ns[segment_index])
    tau = float(np.clip((time_ns - t0) / duration, 0.0, 1.0))
    c0, c1, c2, c3, c4, c5 = source.position_coefficients_mm[segment_index]

    position = c0 + c1 * tau + c2 * tau**2 + c3 * tau**3 + c4 * tau**4 + c5 * tau**5
    velocity = (
        c1 + 2.0 * c2 * tau + 3.0 * c3 * tau**2 + 4.0 * c4 * tau**3 + 5.0 * c5 * tau**4
    ) / duration
    acceleration = (
        2.0 * c2 + 6.0 * c3 * tau + 12.0 * c4 * tau**2 + 20.0 * c5 * tau**3
    ) / duration**2
    return position, velocity / C_MMNS, acceleration / C_MMNS**2


def _light_cone_residual_mm(
    *,
    observer_time_ns: float,
    observer_position_mm: np.ndarray,
    source_time_ns: float,
    source_position_mm: np.ndarray,
) -> tuple[float, float]:
    separation = float(np.linalg.norm(observer_position_mm - source_position_mm))
    residual = C_MMNS * (observer_time_ns - source_time_ns) - separation
    return residual, separation


def _alive_prefix_length(history: _HistoryArrays, source_index: int) -> int:
    """Return the number of source samples before its first loss marker."""

    dead = np.asarray(history.dead[:, source_index], dtype=bool)
    dead_indices = np.flatnonzero(dead)
    if dead_indices.size == 0:
        return int(dead.size)
    first_dead = int(dead_indices[0])
    if np.any(~dead[first_dead:]):
        raise ValueError("source dead-state history must remain dead after loss")
    return first_dead


def _prepare_source_history(
    history: _HistoryArrays, source_index: int
) -> _PreparedSourceHistory:
    """Validate and prepare one source's alive interpolation segments."""

    alive_stop = _alive_prefix_length(history, source_index)
    times = history.time_ns[:alive_stop, source_index]
    positions = history.position_mm[:alive_stop, source_index]
    betas = history.beta[:alive_stop, source_index]
    beta_primes = history.beta_prime_per_mm[:alive_stop, source_index]
    durations = np.diff(times)
    if np.any(durations <= 0.0):
        raise ValueError("source coordinate times must be strictly increasing")

    if durations.size == 0:
        coefficients = np.zeros((0, 6, 3), dtype=float)
    else:
        duration_columns = durations[:, np.newaxis]
        velocity_0 = C_MMNS * betas[:-1]
        velocity_1 = C_MMNS * betas[1:]
        acceleration_0 = C_MMNS**2 * beta_primes[:-1]
        acceleration_1 = C_MMNS**2 * beta_primes[1:]
        c0 = positions[:-1]
        c1 = duration_columns * velocity_0
        c2 = 0.5 * duration_columns**2 * acceleration_0
        position_remainder = positions[1:] - c0 - c1 - c2
        velocity_remainder = duration_columns * velocity_1 - c1 - 2.0 * c2
        acceleration_remainder = duration_columns**2 * acceleration_1 - 2.0 * c2
        c3 = (
            10.0 * position_remainder
            - 4.0 * velocity_remainder
            + 0.5 * acceleration_remainder
        )
        c4 = (
            -15.0 * position_remainder
            + 7.0 * velocity_remainder
            - acceleration_remainder
        )
        c5 = (
            6.0 * position_remainder
            - 3.0 * velocity_remainder
            + 0.5 * acceleration_remainder
        )
        coefficients = np.stack((c0, c1, c2, c3, c4, c5), axis=1)

    return _PreparedSourceHistory(
        source_index=source_index,
        time_ns=times,
        position_mm=positions,
        beta=betas,
        beta_prime_per_mm=beta_primes,
        segment_duration_ns=durations,
        position_coefficients_mm=coefficients,
        ended_by_loss=alive_stop != history.time_ns.shape[0],
    )


def _prepare_history(
    history: TrajectoryHistory,
    excluded_source_indices: Sequence[int],
) -> _PreparedHistory:
    """Extract once and prepare only sources that can contribute a field."""

    arrays = _extract_history(history)
    excluded = {int(index) for index in excluded_source_indices}
    if any(index < 0 or index >= arrays.n_sources for index in excluded):
        raise IndexError("excluded source index is out of bounds")
    sources = {
        source_index: _prepare_source_history(arrays, source_index)
        for source_index in range(arrays.n_sources)
        if source_index not in excluded
        and abs(arrays.charge_native[source_index]) != 0.0
    }
    return _PreparedHistory(arrays=arrays, sources=sources)


def _next_safeguarded_root_trial(
    *,
    trial_time_ns: float,
    residual_mm: float,
    derivative_mm_per_ns: float,
    lower_time_ns: float,
    upper_time_ns: float,
) -> _RootTrialDecision:
    """Take an in-bracket Newton step, or bisect when that step is unsafe."""

    available_time = (
        upper_time_ns - trial_time_ns
        if residual_mm > 0.0
        else trial_time_ns - lower_time_ns
    )
    maximum_newton_residual = -derivative_mm_per_ns * available_time
    if (
        np.isfinite(derivative_mm_per_ns)
        and derivative_mm_per_ns < 0.0
        and np.isfinite(maximum_newton_residual)
        and abs(residual_mm) < maximum_newton_residual
    ):
        next_trial = trial_time_ns - residual_mm / derivative_mm_per_ns
    else:
        next_trial = float("nan")
    if next_trial == trial_time_ns:
        target = upper_time_ns if residual_mm > 0.0 else lower_time_ns
        return _RootTrialDecision(
            time_ns=float(np.nextafter(trial_time_ns, target)),
            used_bisection=False,
            used_nextafter=True,
        )
    if (
        not np.isfinite(next_trial)
        or next_trial <= lower_time_ns
        or next_trial >= upper_time_ns
    ):
        return _RootTrialDecision(
            time_ns=0.5 * (lower_time_ns + upper_time_ns),
            used_bisection=True,
            used_nextafter=False,
        )
    return _RootTrialDecision(
        time_ns=next_trial,
        used_bisection=False,
        used_nextafter=False,
    )


def _solve_retarded_sample(
    source: _PreparedSourceHistory,
    *,
    observer_time_ns: float,
    observer_position_mm: np.ndarray,
    root_tolerance_mm: float,
    max_root_iterations: int,
) -> _RetardedSample | None:
    times = source.time_ns
    if times.size < 2:
        return None

    knot_residuals = np.empty(times.size, dtype=float)
    for index, source_time in enumerate(times):
        knot_residuals[index], _ = _light_cone_residual_mm(
            observer_time_ns=observer_time_ns,
            observer_position_mm=observer_position_mm,
            source_time_ns=float(source_time),
            source_position_mm=source.position_mm[index],
        )
    brackets = np.flatnonzero(
        (knot_residuals[:-1] >= 0.0) & (knot_residuals[1:] <= 0.0)
    )
    if brackets.size == 0:
        return None
    segment = int(brackets[-1])
    lower_time = float(times[segment])
    upper_time = float(times[segment + 1])
    source_position = source.position_mm[segment]
    residual = float(knot_residuals[segment])
    separation = float(np.linalg.norm(observer_position_mm - source_position))
    trial_time = 0.5 * (lower_time + upper_time)

    for _ in range(max_root_iterations):
        source_position, source_beta, source_beta_prime = _quintic_worldline_sample(
            source, segment, trial_time
        )
        residual, separation = _light_cone_residual_mm(
            observer_time_ns=observer_time_ns,
            observer_position_mm=observer_position_mm,
            source_time_ns=trial_time,
            source_position_mm=source_position,
        )
        if abs(residual) <= root_tolerance_mm:
            lower_time = upper_time = trial_time
            break
        if residual > 0.0:
            lower_time = trial_time
        else:
            upper_time = trial_time
        if np.nextafter(lower_time, upper_time) >= upper_time:
            break

        derivative = float("nan")
        if separation > 0.0:
            direction = (observer_position_mm - source_position) / separation
            derivative = -C_MMNS * (1.0 - float(direction @ source_beta))
        decision = _next_safeguarded_root_trial(
            trial_time_ns=trial_time,
            residual_mm=residual,
            derivative_mm_per_ns=derivative,
            lower_time_ns=lower_time,
            upper_time_ns=upper_time,
        )
        trial_time = decision.time_ns

    retarded_time = 0.5 * (lower_time + upper_time)
    source_position, source_beta, source_beta_prime = _quintic_worldline_sample(
        source, segment, retarded_time
    )
    residual, separation = _light_cone_residual_mm(
        observer_time_ns=observer_time_ns,
        observer_position_mm=observer_position_mm,
        source_time_ns=retarded_time,
        source_position_mm=source_position,
    )
    return _RetardedSample(
        time_ns=retarded_time,
        position_mm=source_position,
        beta=source_beta,
        beta_prime_per_mm=source_beta_prime,
        residual_mm=residual,
        separation_mm=separation,
    )


def _source_terminated_before_light_cone(
    source: _PreparedSourceHistory,
    *,
    observer_time_ns: float,
    observer_position_mm: np.ndarray,
) -> bool:
    """Return true when a lost source ended before the required emission event."""

    if not source.ended_by_loss:
        return False
    if source.time_ns.size == 0:
        return True
    last_alive = source.time_ns.size - 1
    residual, _ = _light_cone_residual_mm(
        observer_time_ns=observer_time_ns,
        observer_position_mm=observer_position_mm,
        source_time_ns=float(source.time_ns[last_alive]),
        source_position_mm=source.position_mm[last_alive],
    )
    # g(t_source) decreases monotonically for a timelike worldline. Positive
    # g at the final alive state means the required retarded emission would
    # occur only after the source was removed from the simulation.
    return residual > 0.0


def lienard_wiechert_charge_field_native(
    *,
    charge_native: float,
    separation_vector_mm: Sequence[float],
    source_beta: Sequence[float],
    source_beta_prime_per_mm: Sequence[float],
) -> tuple[np.ndarray, np.ndarray]:
    """Return native scaled-Gaussian ``(E, B)`` for one retarded charge.

    ``source_beta_prime_per_mm`` is ``d beta / d(c t)``. The radiation term
    therefore has no additional factor of ``c``.
    """

    charge = float(charge_native)
    separation_vector = np.asarray(separation_vector_mm, dtype=float)
    beta = np.asarray(source_beta, dtype=float)
    beta_prime = np.asarray(source_beta_prime_per_mm, dtype=float)
    if not np.isfinite(charge):
        raise ValueError("charge_native must be finite")
    for name, vector in (
        ("separation_vector_mm", separation_vector),
        ("source_beta", beta),
        ("source_beta_prime_per_mm", beta_prime),
    ):
        if vector.shape != (3,) or not np.all(np.isfinite(vector)):
            raise ValueError(f"{name} must contain three finite values")
    separation = float(np.linalg.norm(separation_vector))
    if separation <= 0.0:
        raise ValueError("the observer cannot coincide with a point-charge source")
    beta_squared = float(beta @ beta)
    if beta_squared >= 1.0:
        raise ValueError("source beta magnitude must be less than one")
    direction = separation_vector / separation
    kappa = 1.0 - float(direction @ beta)
    if kappa <= 1.0e-14:
        raise ValueError("retarded field is singular because 1 - n.beta is too small")

    velocity_field = (
        (1.0 - beta_squared) * (direction - beta) / (kappa**3 * separation**2)
    )
    radiation_field = np.cross(
        direction,
        np.cross(direction - beta, beta_prime),
    ) / (kappa**3 * separation)
    electric = charge * (velocity_field + radiation_field)
    magnetic = np.cross(direction, electric)
    return cast(tuple[np.ndarray, np.ndarray], (electric, magnetic))


def _validated_root_options(
    root_tolerance_mm: float, max_root_iterations: int
) -> tuple[float, int]:
    tolerance = float(root_tolerance_mm)
    iterations = int(max_root_iterations)
    if not np.isfinite(tolerance) or tolerance <= 0.0:
        raise ValueError("root_tolerance_mm must be finite and positive")
    if iterations <= 0:
        raise ValueError("max_root_iterations must be positive")
    return tolerance, iterations


def _evaluate_prepared_charge_field_native(
    prepared: _PreparedHistory,
    observer_event: ObserverEvent,
    *,
    require_complete_history: bool,
    root_tolerance_mm: float,
    max_root_iterations: int,
) -> RetardedChargeFieldResult:
    """Evaluate one event without extracting or preparing its history again."""

    arrays = prepared.arrays
    observer_time_ns = float(observer_event.time_ns)
    observer_position_mm = np.asarray(observer_event.position_mm, dtype=float)
    electric_total = np.zeros(3, dtype=float)
    magnetic_total = np.zeros(3, dtype=float)
    retarded_time_ns = np.full(arrays.n_sources, np.nan, dtype=float)
    residual_mm = np.full(arrays.n_sources, np.nan, dtype=float)
    separation_mm = np.full(arrays.n_sources, np.nan, dtype=float)
    valid_sources = np.zeros(arrays.n_sources, dtype=bool)
    missing_sources: list[int] = []

    for source_index, source in prepared.sources.items():
        sample = _solve_retarded_sample(
            source,
            observer_time_ns=observer_time_ns,
            observer_position_mm=observer_position_mm,
            root_tolerance_mm=root_tolerance_mm,
            max_root_iterations=max_root_iterations,
        )
        if sample is None:
            if _source_terminated_before_light_cone(
                source,
                observer_time_ns=observer_time_ns,
                observer_position_mm=observer_position_mm,
            ):
                continue
            missing_sources.append(source_index)
            continue
        electric, magnetic = lienard_wiechert_charge_field_native(
            charge_native=float(arrays.charge_native[source_index]),
            separation_vector_mm=observer_position_mm - sample.position_mm,
            source_beta=tuple(float(value) for value in sample.beta),
            source_beta_prime_per_mm=tuple(
                float(value) for value in sample.beta_prime_per_mm
            ),
        )
        electric_total += electric
        magnetic_total += magnetic
        retarded_time_ns[source_index] = sample.time_ns
        residual_mm[source_index] = sample.residual_mm
        separation_mm[source_index] = sample.separation_mm
        valid_sources[source_index] = True

    if require_complete_history and missing_sources:
        raise RetardedHistoryError(
            "source history does not bracket the observer light cone for source "
            f"indices {missing_sources}"
        )
    field_tensor = electromagnetic_field_tensor_native(
        tuple(float(value) for value in electric_total),
        tuple(float(value) for value in magnetic_total),
    )
    return RetardedChargeFieldResult(
        electric_field_native=electric_total,
        magnetic_field_native=magnetic_total,
        field_tensor=field_tensor,
        retarded_time_ns=retarded_time_ns,
        light_cone_residual_mm=residual_mm,
        separation_mm=separation_mm,
        valid_sources=valid_sources,
    )


def evaluate_retarded_charge_field_native(
    history: TrajectoryHistory,
    observer_event: ObserverEvent,
    *,
    excluded_source_indices: Sequence[int] = (),
    require_complete_history: bool = True,
    root_tolerance_mm: float = _DEFAULT_ROOT_TOLERANCE_MM,
    max_root_iterations: int = _DEFAULT_MAX_ROOT_ITERATIONS,
) -> RetardedChargeFieldResult:
    """Evaluate the summed native Gaussian charge field at one event."""

    tolerance, iterations = _validated_root_options(
        root_tolerance_mm, max_root_iterations
    )
    prepared = _prepare_history(history, excluded_source_indices)
    return _evaluate_prepared_charge_field_native(
        prepared,
        observer_event,
        require_complete_history=require_complete_history,
        root_tolerance_mm=tolerance,
        max_root_iterations=iterations,
    )


def evaluate_retarded_charge_field_gradient_native(
    history: TrajectoryHistory,
    observer_event: ObserverEvent,
    *,
    excluded_source_indices: Sequence[int] = (),
    require_complete_history: bool = True,
    relative_step: float = _DEFAULT_GRADIENT_RELATIVE_STEP,
    minimum_step_mm: float = _DEFAULT_GRADIENT_MINIMUM_STEP_MM,
    root_tolerance_mm: float = _DEFAULT_ROOT_TOLERANCE_MM,
    max_root_iterations: int = _DEFAULT_MAX_ROOT_ITERATIONS,
) -> RetardedChargeFieldGradientResult:
    """Evaluate F and its complete centered spacetime derivative.

    partial_f[lambda, mu, nu] is partial_lambda F^(mu nu) for
    x=(ct,x,y,z) in millimetres. Every displaced event independently re-solves
    every source light cone.
    """

    relative = float(relative_step)
    minimum = float(minimum_step_mm)
    if not np.isfinite(relative) or relative <= 0.0 or relative >= 0.1:
        raise ValueError("relative_step must be finite and in (0, 0.1)")
    if not np.isfinite(minimum) or minimum <= 0.0:
        raise ValueError("minimum_step_mm must be finite and positive")
    tolerance, iterations = _validated_root_options(
        root_tolerance_mm, max_root_iterations
    )
    prepared = _prepare_history(history, excluded_source_indices)
    center = _evaluate_prepared_charge_field_native(
        prepared,
        observer_event,
        require_complete_history=require_complete_history,
        root_tolerance_mm=tolerance,
        max_root_iterations=iterations,
    )
    finite_separations = center.separation_mm[center.valid_sources]
    if finite_separations.size == 0:
        stencil_step = minimum
    else:
        stencil_step = max(minimum, relative * float(np.min(finite_separations)))

    partial_f = np.zeros((4, 4, 4), dtype=float)
    retarded_times = np.full((4, 2, center.retarded_time_ns.size), np.nan, dtype=float)
    center_position = np.asarray(observer_event.position_mm, dtype=float)
    for derivative_index in range(4):
        fields = []
        for sign_index, sign in enumerate((-1.0, 1.0)):
            if derivative_index == 0:
                displaced = ObserverEvent(
                    time_ns=(
                        float(observer_event.time_ns) + sign * stencil_step / C_MMNS
                    ),
                    position_mm=observer_event.position_mm,
                )
            else:
                displaced_position = center_position.copy()
                displaced_position[derivative_index - 1] += sign * stencil_step
                displaced_position_tuple = cast(
                    tuple[float, float, float],
                    tuple(float(value) for value in displaced_position),
                )
                displaced = ObserverEvent(
                    time_ns=float(observer_event.time_ns),
                    position_mm=displaced_position_tuple,
                )
            field = _evaluate_prepared_charge_field_native(
                prepared,
                displaced,
                require_complete_history=require_complete_history,
                root_tolerance_mm=tolerance,
                max_root_iterations=iterations,
            )
            fields.append(field.field_tensor)
            retarded_times[derivative_index, sign_index] = field.retarded_time_ns
        partial_f[derivative_index] = (fields[1] - fields[0]) / (2.0 * stencil_step)

    return RetardedChargeFieldGradientResult(
        field=center,
        partial_f=partial_f,
        stencil_step_mm=stencil_step,
        stencil_retarded_time_ns=retarded_times,
    )


__all__ = [
    "ObserverEvent",
    "RetardedChargeFieldGradientResult",
    "RetardedChargeFieldResult",
    "RetardedHistoryError",
    "evaluate_retarded_charge_field_gradient_native",
    "evaluate_retarded_charge_field_native",
    "lienard_wiechert_charge_field_native",
]
